### ISSUE TITLE
openshift 上运行失败

### ISSUE THREAD

**Issue by 523860169** [lzghzr/bilive_client#1]
![default](https://cloud.githubusercontent.com/assets/6436073/23099553/31ad7d60-f6a5-11e6-890e-22fb74765c76.PNG)

**Comment by 523860169** [comment]
http://stackoverflow.com/questions/20974094/openshift-node-js-error-listen-eacces
http://stackoverflow.com/questions/18171542/error-listen-eacces-on-openshift-app
我google到这两条可能的解决办法，但不知道是否有效

**Comment by 523860169** [comment]
我改了option.js第67行为：
`        this._http.listen(10080, process.env.OPENSHIFT_NODEJS_IP || '127.0.0.1', () => {
`
但是提示：
![default](https://cloud.githubusercontent.com/assets/6436073/23101830/f523e540-f6d7-11e6-9927-3b9f22f99123.PNG)
所以接下来怎么改

**Comment by lzghzr** [comment]
@523860169 第一个问题，因为没考虑过openshift，也没考虑到报错，不过感谢提供解决方法。
第二个问题应该是离弹幕服务器太远了，你可以试一下
`ping livecmt-2.bilibili.com`

**Comment by 523860169** [comment]
![default](https://cloud.githubusercontent.com/assets/6436073/23101922/f7ec62aa-f6d9-11e6-8807-ee77b3b8ee65.PNG)

**Comment by 523860169** [comment]
你可以搭建一个openshift的试试，不要选nodejs 0.10，选择nodejs(latest)就可以了

**Comment by lzghzr** [comment]
@523860169 程序是四部分，一部分(lottery)是监听弹幕服务器，获取系统广播用来自动参与小电视和其他抽奖，这部分用的是socket长连接，容易断开因为B站没用全球CDN。另一部分(online)是模拟PC和客户端在线，挂活动道具，自动领宝箱，也就是加经验，因为B站使用了全球CDN所以国外也比较稳定。第三部分(options)就是用户设置了，直接改options.json也可以。
时间没影响，程序每8小时进行一次签到，并不是固定时间

**Comment by 523860169** [comment]
@lzghzr 所以没有连接上弹幕服务器只是影响小电视之类的抽奖，但是签到、领瓜子什么的是不影响的，所以这样的话，挂机的意义就变成单纯的加经验了。
对了我在script.js还发现有127.0.0.1，那个是不是也要随着option.js里的改动同步更改？怎么改才可以，我试着改了几次，但是都不知道是否成功了，因为运行日志输出没有任何变化，所以不知道是否改对了。

**Comment by 523860169** [comment]
我刚刚突然发现，好像不会自动领每日礼包和周常礼包啊

**Comment by lzghzr** [comment]
@523860169 view里的都和设置有关，修改options.json或者在其他电脑修改完再拷过来就行，而且也不建议直接把设置界面放在公网上，毕竟密码都是明文的。
每日礼包之前有，但是发现领取记录是在cookie里的，也就是程序自动领完，手动打开包裹还是会弹出提示，索性就去掉了

**Comment by 523860169** [comment]
了解了，谢谢

**Comment by 523860169** [comment]
我觉得是不是可以增加一个自动送当天过期礼物给默认房间的功能，有的时候忘记了，就浪费了，觉得好可惜呢

**Comment by diaosimiao** [comment]
您好,请问一下部署到openshift上对原文件需要修改增加些什么.(步骤详细点说说更好,或者给几个链接范例我研究下,当然能传上来共享更感谢),正在研究把lzghzr大佬写的nodef部署到云服务器.谢谢您!!!
@523860169 自动送礼物这里有,我部署好自动送成功了(PHP).https://github.com/CHEATBEATER/bilibili-live-php

**Comment by 523860169** [comment]
只要3楼那个改一下就可以用了，就是弹幕服务器不能用，也就不能自动抽奖什么的

**Comment by diaosimiao** [comment]
@523860169 刚上线,谢谢吧主热心及时回复,开电脑继续部署.希望苦手能成功.

**Comment by diaosimiao** [comment]
@523860169 搞定了,全功能.什么都不用改.部署的时候不要部署成web,因为“web”类型的应用程序必须监听一些端口,直接部署成"worker"所有功能实现.膜拜感谢lzghzr大佬!!!谢谢吧主提示!!!苦手五体投地膜拜你们!
