### ISSUE TITLE
如何减少或者避免被封

### ISSUE THREAD

**Issue by superybq** [lzghzr/bilive_client#102]
经常挂几个小时第二天就发现被封了,有什么方法可以减少/避免被封吗

**Comment by superybq** [comment]
@Pumilk 我丢失设置的30,暂停抽奖设置的0,12,延时设置的15000,还是效果不明显,改哪个比较好?

**Comment by Pumilk** [comment]
@superybq 
我丢失80，暂停是2,7。
我觉得抽奖的时间只要不是凌晨都在抽应该没什么问题，关键应该还是每天抽的是不是太狠了点。
因为我之前试了一次把丢失设成0，然后抽了一天第二天还是什么时候就小黑屋了……设成80后几个月来我的号一共就3次小黑屋。
我觉得可以模仿一下正常用户的抽奖习惯，比如中午12-13丢失20，12-19丢失80来模拟偶尔去抽个奖的感觉，不过觉得收益应该差不了太多(雾)

**Comment by AdiEcho** [comment]
@Pumilk 你这么设置的话一天少了不少辣条哇，虽然很稳就是了

**Comment by dust0517** [comment]
该**封禁** 的跑不了，尽量 **少使用** 抽奖，单纯挂经验的号要和辣条机分开

**Comment by superybq** [comment]
我现在这是丢弃率50貌似还行.B站管的太严了

**Comment by guidongliang** [comment]
封禁了怎么解封鸭~
