### ISSUE TITLE
关于监听节奏风暴的远程服务器地址

### ISSUE THREAD

**Issue by JerryRich** [lzghzr/bilive_client#11]
这个地址和其apikey是啥

**Comment by lzghzr** [comment]
目前还没有开放的打算，以及以现在的情况，开放了也不一定抢得到
不过这几天服务器ip陆续被封，如果B站态度很强硬的话会考虑开源服务器部分

**Comment by JerryRich** [comment]
@lzghzr 也就是说现在还不能自动抽取节奏风暴吗

**Comment by lzghzr** [comment]
@JerryRich 嗯，是的
