### ISSUE TITLE
更新之后不抽奖了

### ISSUE THREAD

**Issue by congyifeng** [lzghzr/bilive_client#111]
和没登陆的时候一样，只报抽奖信息，不抽奖

**Comment by lzghzr** [comment]
因为加了暴力发包，有日志的话会非常乱，所以暂时没加
________________________________

**Comment by lzghzr** [comment]
目前提交的版本在不启用暴力发包的时候会有日志

**Comment by zreo147** [comment]
@lzghzr    看了新版本，怎么更换服务端啊....

**Comment by lzghzr** [comment]
有人提供或者自己搭建的话，直接设置里更新就可以了
________________________________

**Comment by zreo147** [comment]
@lzghzr    自己搭建的，服务端和客户端在同一服务器

**Comment by zreo147** [comment]
看到之前是wss://bilive.halaal.win/server/#164c48292a6c773c85716093589cd60e

**Comment by zreo147** [comment]
之后修改为wss://服务器IP，127.0.0.1/server/#然后是用户子协议         这样的修改对么，一直链接不上

**Comment by lzghzr** [comment]
ws://localhost:20080/#用户子协议
________________________________
