### ISSUE TITLE
更新之后,辣条抽奖变少

### ISSUE THREAD

**Issue by yx1319250478** [lzghzr/bilive_client#112]
更新之后,有了上船亲密度,但是辣条抽奖从日志上看好像比以前少了,不知道是不是错觉

**Comment by lzghzr** [comment]
没统计过

**Comment by cris3980** [comment]
看了一下确实会有这种情况，辣条的好像都没抽一样，只有偶尔几根

**Comment by lzghzr** [comment]
应该不存在这种情况，我这里统计的辣条抽奖只有几百个，大多数是舰长和节奏风暴

**Comment by cris3980** [comment]
我还特意对比了别的分支，辣条数量只有别的分支1/3左右

**Comment by lzghzr** [comment]
22日的 第一个抽奖是186605，最后一个是187167，一共562个
账号里辣条808个，没感觉有什么问题

**Comment by cris3980** [comment]
没黑屋的账号包裹都只有300左右....

**Comment by lzghzr** [comment]
直接打开开关就行了

2018年11月24日 14:25，WangMuDu <notifications@github.com>道：

话说 如果直接升级覆盖的话 配置有什么需要改的吗 还是直接就能正常启动 只需要打开开关就行了

―

**Comment by yx1319250478** [comment]
用了最新的版本之后，辣条数量正常了，亿元变少了

**Comment by lzghzr** [comment]
亿元和账户有关，如果新号或者很久没抢过的就会多，经常抢的就没多少了

2018年11月24日 14:32，yx1319250478 <notifications@github.com>寫道：

用了最新的版本之后，辣条数量正常了，亿元变少了

**Comment by lovezm** [comment]
出现了整个服务器都不抽奖的情况

**Comment by lovezm** [comment]
但是亲密度正常是为啥

**Comment by cris3980** [comment]
是的，很奇怪，昨天更新2.0之后甚至一根辣条都没有了，只有亲密度

**Comment by lovezm** [comment]
> 是的，很奇怪，昨天更新2.0之后甚至一根辣条都没有了，只有亲密度

我也是

**Comment by lovezm** [comment]
回退了也没有了

**Comment by lzghzr** [comment]
嗯……我关注一下

**Comment by lovezm** [comment]
我盯了很久  亿圆和舰长都抽的起劲  辣条的广播一直刷 就是不抽 - -
