### ISSUE TITLE
最新版本模块bootstrap与jquery不兼容

### ISSUE THREAD

**Issue by Vector000** [lzghzr/bilive_client#117]
![default](https://user-images.githubusercontent.com/33326900/49697825-fa9e3900-fbf6-11e8-97d7-010813bb6732.PNG)
如题，两模块不兼容，编译会报错；应该是新jquery的锅。实测将`package.json:21`改为`"@types/jquery": "3.3.22"`可以暂时回避这个问题

**Comment by lzghzr** [comment]
我看看能不能去掉jQuery的依赖，说实话我是不太喜欢这个东西的

**Comment by lzghzr** [comment]
话说有没有比较合适的ui框架推荐一下？

**Comment by Vector000** [comment]
我之前玩过一下子vuetify，是依赖于vue.js的，还做过一个bilive_electron的打包成桌面端的小玩意
有兴趣的话可以去看看xd

**Comment by lzghzr** [comment]
vue之前想了解来的, 不过想想还是太麻烦了
前天看了一眼bootstrap.native, 对父节点为DocumentFragment的支持的不好, 直接报错
