### ISSUE TITLE
本地电脑配置成功之后复制options进服务器启动失败

### ISSUE THREAD

**Issue by Naexen** [lzghzr/bilive_client#123]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle bilive_client@2.0.1~prestart: bilive_client@2.0.1
6 info lifecycle bilive_client@2.0.1~start: bilive_client@2.0.1
7 verbose lifecycle bilive_client@2.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle bilive_client@2.0.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Administrator\Desktop\renew\bilive_client201\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\QCloud\Monitor\Barad;C:\Program Files\nodejs\;C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\;C:\Users\Administrator\AppData\Roaming\npm
9 verbose lifecycle bilive_client@2.0.1~start: CWD: C:\Users\Administrator\Desktop\renew\bilive_client201
10 silly lifecycle bilive_client@2.0.1~start: Args: [ '/d /s /c', 'node app.js' ]
11 silly lifecycle bilive_client@2.0.1~start: Returned: code: 1  signal: null
12 info lifecycle bilive_client@2.0.1~start: Failed to exec start script
13 verbose stack Error: bilive_client@2.0.1 start: `node app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid bilive_client@2.0.1
15 verbose cwd C:\Users\Administrator\Desktop\renew\bilive_client201
16 verbose Windows_NT 6.3.9600
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.10.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error bilive_client@2.0.1 start: `node app.js`
22 error Exit status 1
23 error Failed at the bilive_client@2.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Naexen** [comment]
1

**Comment by Naexen** [comment]
https://1drv.ms/u/s!AlEAXCo7piSkiWJow_ks_5yWt_DT

**Comment by Naexen** [comment]
https://pan.baidu.com/s/1tA1IdrQJExhzaUy4Rmw3Eg

**Comment by Naexen** [comment]
btw新的可以打开但是进不去设置 怎么改端口都是连接失败

**Comment by Naexen** [comment]
救救孩子叭

**Comment by lzghzr** [comment]
日志报错不知道怎么贴代码的话最好截图，这个看得我头疼
连接失败你可以看一下浏览器报错
________________________________

**Comment by tzhongyan** [comment]
尝试了一下，应该是服务器上没进行`npm run build`
执行以上命令应该能够解决你的问题

**Comment by Naexen** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose stack Error: missing script: build
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:402:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:357:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:400:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:332:20)
4 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
5 verbose cwd C:\Users\Administrator\Desktop\renew\bilive_client201
6 verbose Windows_NT 6.3.9600
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
8 verbose node v8.10.0
9 verbose npm  v5.6.0
10 error missing script: build
11 verbose exit [ 1, true ]

**Comment by Naexen** [comment]
https://pastebin.com/HtHUJLU0 一楼的
https://pastebin.com/HY8VrH6b 刚才的

**Comment by Vector000** [comment]
粗略看了一下，你的node版本太低，需要更新

发送自 Windows 11 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Naexen <notifications@github.com>
发送时间: Monday, February 25, 2019 7:50:36 PM
收件人: lzghzr/bilive_client
抄送: Subscribed
主题: Re: [lzghzr/bilive_client] 本地电脑配置成功之后复制options进服务器启动失败 (#123)


https://pastebin.com/HtHUJLU0 一楼的
https://pastebin.com/HY8VrH6b 刚才的

―

**Comment by Naexen** [comment]
更新node版本后成功进入了，麻烦各位大佬了。感激不尽！
