### ISSUE TITLE
新分区

### ISSUE THREAD

**Issue by 00sky** [lzghzr/bilive_client#126]
大佬，现在分区变成六个分区了。能加个实时获取6个分区正在直播的房间吗？

**Comment by lzghzr** [comment]
我记得是会自动加上的吧
________________________________

**Comment by 00sky** [comment]
和那个挂机活动房间没关系是吗？

**Comment by lzghzr** [comment]
没关系，那个是历史遗留下来的，现在没用了
________________________________

**Comment by 00sky** [comment]
哦哦哦，好的，谢谢大佬解答

**Comment by lovezm** [comment]
催更，偶尔不签到了 2333

**Comment by lovezm** [comment]
看了一下好像是00:10执行签到  可以每天执行两次吗  中午再来一次
