### ISSUE TITLE
日常任务完成不了

### ISSUE THREAD

**Issue by syu1230** [lzghzr/bilive_client#128]
![1](https://user-images.githubusercontent.com/41249793/55071688-400e4580-50c4-11e9-9860-cd8dd66c4d41.png)
今天个别帐号突然出现这个问题，之前都正常的。登上帐号看了一下，是网页端的观看没完成，请问下这是什么情况？

**Comment by lzghzr** [comment]
似乎是token没有刷新

**Comment by syu1230** [comment]
有解决办法么，出现的变多了

**Comment by Vector000** [comment]
我也遇到了这个问题，同时挂机有时候几个号都报这个错误
日常任务这一块其实是调用的web端的一个api，依靠的是cookie，跟token貌似关系不大，怀疑破站日常抽风
目前发现改用GET请求貌似可行，我先测试几天看看

**Comment by lzghzr** [comment]
一次不行就两次，我也打算把直播日常任务限制取消了，直接每天三次爱咋咋地
________________________________

**Comment by syu1230** [comment]
多次启动也还是那样，怎么改用GET请求
