### ISSUE TITLE
脚本提示某某房间赠送小电视 但并没有参与抽奖

### ISSUE THREAD

**Issue by yimshing** [lzghzr/bilive_client#13]
刚用的几天能正常抽辣条 但后来就只是提示某某房间赠送小电视 但没有中了什么的提示
确定设置那里是true的

**Comment by lzghzr** [comment]
也许B站改了链接，我看一眼

**Comment by lzghzr** [comment]
不是我的锅
![小电视](https://ws1.sinaimg.cn/large/005GMXCNly1fk8wshd5ftj30ne074gni.jpg)

**Comment by lzghzr** [comment]
目前B站修复了上面的问题，但是依然无法参与，不知道是进黑名单了还是B站bug
