### ISSUE TITLE
謝謝作者(°∀°)ﾉ

### ISSUE THREAD

**Issue by brina60602** [lzghzr/bilive_client#14]
今天節奏風暴我拿到了45個億圓~
前幾天都完全拿不到  不知今天是怎麼了(｀・ω・´)

**Comment by lzghzr** [comment]
大概是工作室被封掉了？最近B站动作蛮多的，应该是决心搞掉脚本吧

**Comment by brina60602** [comment]
_(:3」∠)_ 不知以後還能不能用...

**Comment by lzghzr** [comment]
节奏风暴功能我会在十一长假以后关掉，因为总有人问，所以我就限时开放一下
