### ISSUE TITLE
app.js是.ts用node.js打開閃退

### ISSUE THREAD

**Issue by kikulove** [lzghzr/bilive_client#16]
![nywjx sythw 32ioqac6m](https://user-images.githubusercontent.com/30995704/32431551-efb6b476-c30e-11e7-8a4f-4d53730506df.png)
能加qq联系下吗

**Comment by kikulove** [comment]
qq2496574352

**Comment by lzghzr** [comment]
不会编译的话就直接下载[bilive_client.zip](https://github.com/lzghzr/bilive_client/releases)使用

**Comment by kikulove** [comment]
![sv u6 hsrhedagxr omh2j](https://user-images.githubusercontent.com/30995704/32435932-669e84ac-c31d-11e7-8c9c-98da3d7d3aa0.png)
出现了这个

**Comment by lzghzr** [comment]
请读完[README](https://github.com/lzghzr/bilive_client/blob/master/README.md)的五句话

**Comment by kikulove** [comment]
解压并定位到目录是任意的位置都可以吗。運行npm install是这个吗。
![n af08 25t40gbp 2cr96yt](https://user-images.githubusercontent.com/30995704/32441692-a8cce1e6-c333-11e7-8f40-476ab5c384b7.png)

**Comment by lzghzr** [comment]
嗯……我有时间把介绍写详细一些吧

**Comment by tzhongyan** [comment]
看来楼主是不明白“解压并定位到目录”这个操作，我简单地说下windows的步骤吧：
1. 在[这里](https://github.com/lzghzr/bilive_client/releases)下载以后，解压到任何一个目录
2. 启动cmd：Win键+R，输入`cmd`然后回车
3. **定位到目录**：`cd [解压以后的目录]`，不确定目录在哪里的话可以直接抄下地址粘接上去

然后就应该可以运行`npm install` 及 `node app.js`

另外建议作者大大能够把编译的plugin加入`devDependency`，然后给我们加个`npm run build`直接编译啥的 /滑稽

**Comment by lzghzr** [comment]
@tzhongyan 看了一下，npm原来还有这功能

**Comment by kikulove** [comment]
@lzghzr  怎麼運行npm install和node app.js啊。上网查了npm的安装和环境变量什么的，但是还是打不开app.js

**Comment by Vector000** [comment]
...这个issue可以close了吧...强迫症表示ㄟ( ▔, ▔ )ㄏ
