### ISSUE TITLE
服务器节奏风暴功能

### ISSUE THREAD

**Issue by dawnspace** [lzghzr/bilive_client#19]
请问节奏风暴现在是处于关闭状态吗。。。还有这个服务器能够自定义么

**Comment by lzghzr** [comment]
节奏风暴目前是开启状态
服务端不开源, 应该没有其他可用

**Comment by dawnspace** [comment]
开启状态为啥我一点提示也没有.....除了输入服务器地址和key之外还有别的操作吗😳

**Comment by lzghzr** [comment]
不需要，提示连接成功就行
昨天开始就没有节奏风暴了，原因未知

**Comment by dawnspace** [comment]
_(:зゝ∠)_好的，谢谢啦
