### ISSUE TITLE
1.1.1 node:688

### ISSUE THREAD

**Issue by zanewayne78** [lzghzr/bilive_client#20]
(node:688)  UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: First argument should be a valid curve name
(node:688) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
这是什么意思 ？

**Comment by zanewayne78** [comment]
回滚上上一版了

**Comment by lzghzr** [comment]
因为node版本和ws不兼容，建议使用最新LTS
