### ISSUE TITLE
做了個能開機自啟的批次檔(°∀°)ﾉ

### ISSUE THREAD

**Issue by brina60602** [lzghzr/bilive_client#21]
要照自己放的位置修改
做好放windows的啟動資料夾就能開機自啟了(｀・ω・´)
![bilive_client](https://user-images.githubusercontent.com/15816106/33232604-0a0e43c2-d244-11e7-9de9-b91c044643d3.png)

**Comment by zanewayne78** [comment]
学习了，还有这种操作

**Comment by lzghzr** [comment]
因为有一部分人拿服务器挂机，所以window脚本并不适用
