### ISSUE TITLE
小电视及活动礼物的连击问题

### ISSUE THREAD

**Issue by Vector000** [lzghzr/bilive_client#25]
这几天晚上实测当同一用户一次送多个小电视或丰收祭典时只能监听到第一个电视的消息，无法全部参与。

**Comment by catbule** [comment]
正想反馈这个问题

**Comment by zanewayne78** [comment]
`与监听服务器断开五分钟_` `尝试重新连接服务器失败`

**Comment by lzghzr** [comment]
因为这种情况很少，所以偷懒没写

root <notifications@github.com> 于 2017年11月30日周四 02:45写道：

**Comment by lzghzr** [comment]
更新把这个写上去了
