### ISSUE TITLE
网页端设置的问题

### ISSUE THREAD

**Issue by BenZinaDaze** [lzghzr/bilive_client#26]
网页设置连接后网页空白，看控制台访问127.0.0.1:10080一直是Pending，状态是101;
直接访问http://127.0.0.1:10080 是可以访问的;
nodejs版本是8.5，npm版本是5.3;
还有`npm install` 一直少装一个库，加上参数`-g` 才装上.

**Comment by BenZinaDaze** [comment]
现在是
`Failed to load resource: the server responded with a status of 404 ()`

**Comment by lzghzr** [comment]
因为用了websocket啊，连接成功就是101的，不是200

**Comment by BenZinaDaze** [comment]
控制台一直这个
`options.ts:97 MessageEvent {isTrusted: true, data: "{"cmd":"options","data":{"defaultUserID":null,"def… 电话, 清空包裹, 刷广告等等你想得到和想不到的事情","type":"boolean"}}}}", origin: "ws://127.0.0.1:10080", lastEventId: "", source: null, …}`

**Comment by tzhongyan** [comment]
看README，新版的[在这个网页](https://lzghzr.github.io/bilive_client_view/index.html)设置。
其实也可以下载那个网页到自己电脑里面，再进行设置

**Comment by BenZinaDaze** [comment]
就是在这个网页设置的，点连接后网页就变成空白了。控制台出现上面的错误了

**Comment by diaosimiao** [comment]
先感谢lzghzr 大大的开源和持续更新。
还是之前的1.1.1旧版-服务器没问题，今天突然发现监听服务器断开。
于是使用新版网页设置，也是连不上来反馈。

**Comment by selfler** [comment]
好像更新不了cookie。。过期了登不上

**Comment by zanewayne78** [comment]
监听服务器断开，cookie过期不能马上更新，电视礼物收不到，怎么回事啊作者大大 @lzghzr

**Comment by Vector000** [comment]
觉得是B站修改了小电视的获取方法，可以看看我submit的 #27

**Comment by Vector000** [comment]
觉得是B站修改了小电视的获取方法，可以看看我submit的 #27

**Comment by liansishen** [comment]
cookie不更新的问题，改一下online文件里的心跳方法，返回code=3的时候返回cookie错误

**Comment by lzghzr** [comment]
可以用最新版了，设置和以前不一样，以及修复了cookie的问题

**Comment by BenZinaDaze** [comment]
新版没问题，谢谢作者lzghzr
