### ISSUE TITLE
B站小电视参与方法的修改

### ISSUE THREAD

**Issue by Vector000** [lzghzr/bilive_client#27]
昨晚晚些时候发现client的log只能监听小电视信息但不能参与抽奖，怀疑B站对参与方法进行了修改。于是使用浏览器f12查看，发现参与小电视抽奖的方法似乎换了。

现在的是`http://api.live.bilibili.com/gift/v2/smalltv/join?roomid=$(RoomID)&id=$(raffleID)`
而之前的是`http://api.live.bilibili.com/SmallTV/join/roomid=${this._roomID}&id=${this._raffleId}&_=${Date.now()}`
另外发现获取抽奖结果返回值的方法亦有修改，现在的是`http://api.live.bilibili.com/gift/v2/smalltv/notice?roomid=$(RoomID)&raffleId=$(raffleID)`

以上方法在我的chrome上测试通过，能够参与并获取小电视抽奖及其结果。然而我萌新，没办法完成对现行js脚本的修改=￣ω￣=希望大佬完成

BTW，貌似祭典活动也修改了？现在的进入好像是`http://api.live.bilibili.com/activity/v1/Raffle/join?roomid=$(RoomID)&raffleId=$(raffleID)`
跟之前的比对发现时间项`${Date.now()}`貌似没用了2333

另外发现小电视礼物返回值格式也改了，向祭典礼物看齐，看来B站是要统一礼物格式了

**Comment by lzghzr** [comment]
感谢告知，等B站改完稳定了就跟进

Vector000 <notifications@github.com> 于 2017年12月1日周五 02:30写道：

**Comment by lzghzr** [comment]
已经更新

**Comment by Vector000** [comment]
感谢作者大大更新（￣︶￣）↗　

话说今天早上我一直在试图通过修改脚本达到抽电视的目的。大概就是把index.js:`exports.smallTVPathname = '/gift/v2/smalltv'`这个改了下，然后把raffle.js的`join.uri`改了下，发现并没有什么用＞︿＜

看了下大大的代码，发现新版使用了`SmallTV() {
        this._url = index_1.apiLiveOrigin + index_1.smallTVPathname;
        return this._Raffle();
    }
    Raffle() {
        this._url = index_1.apiLiveOrigin + index_1.rafflePathname;
        return this._Raffle();
    }`的用法，不知跟这个有什么关系？还是因为cookie传递的问题？因为listener.js那边感觉没啥问题这样改又没办法提交正确的请求...萌新求大佬解惑解惑(～￣▽￣)～

**Comment by lzghzr** [comment]
因为B站统一了小电视和抽奖的请求和返回，所以就写在一起了。
你改的没错，可以正确提交请求，但是因为返回的改变，不能正确处理，也就不能到获取结果这一步

Vector000 <notifications@github.com> 于 2017年12月1日周五 21:43写道：

**Comment by Vector000** [comment]
感谢大佬，现在更新后礼物连击也能自动抽了，然后我忘记挂脚本了...

话说现在改了设置逻辑将来有无可能做成多终端的挂机形式，或者添加自动送礼、返回当前UID信息、统计啥的（好像有点多了233）

**Comment by lzghzr** [comment]
更改逻辑主要是为了解决登录验证码和服务器挂机远程管理的问题。自动送礼在考虑范围，统计应该不会弄，太麻烦又没有啥收益

Vector000 <notifications@github.com> 于 2017年12月2日周六 09:44写道：
