### ISSUE TITLE
请问lzghzr大大heroku上现在怎么修改，感谢

### ISSUE THREAD

**Issue by diaosimiao** [lzghzr/bilive_client#28]
原来大大教把options.js那行改成
this._http.listen(process.env.PORT, () => {
一直连接很好，现在版本options.js  heroku报错
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: EROFS: read-only file system, mkdir '/app/bilive/lib/../../../options/'
 at Object.fs.mkdirSync (fs.js:885:18)
at Options.Promise (/app/bilive/lib/tools.js:71:16)
at new Promise (<anonymous>)
at Object.Options (/app/bilive/lib/tools.js:68:12)
at BiLive.Start (/app/bilive/index.js:14:34)
at Object.<anonymous> (/app/app.js:4:8)
 at Module._compile (module.js:635:30)
at Object.Module._extensions..js (module.js:646:10)
at Module.load (module.js:554:32)
at tryModuleLoad (module.js:497:12)

然后
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
我很笨试着把以前能运行的options.js复制回去还是一样的提示
我本身能力有限，修改了多次无法成功，只能求助下大大了。
马飞难受！lzghzr牛逼！！！

**Comment by lzghzr** [comment]
现在options.json在和bilive同路径的options目录里，权限不足可以手动新建一个。监听的端口设置在options.json里手动修改

diaosimiao <notifications@github.com> 于 2017年12月2日周六 16:27写道：

**Comment by tzhongyan** [comment]
尝试了一下用Heroku挂机，发现heroku会把所有的websocket的流量转换成http，所以好像没办法用网页设置。
如果非要用heroku的话，可以先行把`options/options.json`设置好，再从`heroku run bash`设置heroku上的`options/options.json`。

源代码：
https://github.com/tzhongyan/bilive_client/tree/3b448615e8ee06ca10ed2e5b34d7d9e476fe1850
上传之后设置`options.json`，再以`heroku ps:scale bot=1`启动，还没尝试24小时候自动启动的情况
*（对typescript不太熟悉，就别管build的错误了）*

**Comment by diaosimiao** [comment]
@tzhongyan 
我是在bilive_client文件夹下新建了个ecosystem.json利用pm2控制重启时间
{
  "apps":
    {
"cwd": "/",
"script": "./app.js",
"max_memory_restart": "100M",
"cron_restart": "2 */4 * * *"
    }
}

然后package.json里加入 
  "scripts": {
    "start": "pm2 startOrRestart ecosystem.json --attach",
"dependencies": {
 "pm2": "^2.8.0",

Procfile就是正常的 worker: npm start
最后利用监控360网站服务监控，10分钟监控一次网页防止休眠。
真新人完全不懂编程，在这里向大佬们低头，谢谢你们的付出！！！

**Comment by diaosimiao** [comment]
我是咸鱼，昨晚改到现在，ubuntu-16.04.3系统不管怎么设置权限和重建文件上传运行都提示错误（这是最少的就2条错误）
(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: EROFS: read-only file system, mkdir '/app/bilive/lib/../../../options/'

app[web.1]: (node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
佩服你们码子大佬，修仙党去睡觉了，乾杯- ( ゜- ゜)つロ~-向程序缘低头！

**Comment by lzghzr** [comment]
更新了一下，应该是可以用了，测试地址 https://stormy-lowlands-16756.herokuapp.com

**Comment by diaosimiao** [comment]
lzghzr牛逼，我永远搞不定的，你一下就搞定。感谢！！！终于能睡觉了，谢谢大佬 @lzghzr

**Comment by lzghzr** [comment]
只是因为代码写的太垃圾别人看不懂也没法改

diaosimiao <notifications@github.com> 于 2017年12月3日周日 19:02写道：
