### ISSUE TITLE
install安装时no repository filed

### ISSUE THREAD

**Issue by zanewayne78** [lzghzr/bilive_client#3]
怎么解决，求教

**Comment by lzghzr** [comment]
@zanewayne78 这个提示没关系吧，不是提示找不到package.json就行

**Comment by zanewayne78** [comment]
但是不能用，node app.js就会出现下图 @lzghzr 
![2017-04-14_071655](https://cloud.githubusercontent.com/assets/27408421/25027964/1d3996bc-20e3-11e7-9965-5993b954e105.png)

**Comment by lzghzr** [comment]
@zanewayne78 嗯，，我又少放了一个文件进去，已经重新上传了
