### ISSUE TITLE
B站又乱改返回值

### ISSUE THREAD

**Issue by Vector000** [lzghzr/bilive_client#33]
今天上线的新活动，实测发现B站对`dataJson.giftId`的返回值进行了修改

我将listener.js:47中的`if (dataJson.giftId === 103)`修改为`if (dataJson.giftId === 106)`后可以正常抽火力票，大大可以更新一波

嘛，破站就知道瞎改ㄟ( ▔, ▔ )ㄏ

**Comment by lzghzr** [comment]
感谢，这个我暂时没想到好方法，所以只能每次手动更新了

Vector000 <notifications@github.com> 于 2017年12月6日周三 17:19写道：

**Comment by Vector000** [comment]
改个值还好，重新编译麻烦啊

**Comment by lzghzr** [comment]
改好了，这个值是活动的礼物ID，每次活动都会变(・.・;)

Vector000 <notifications@github.com> 于 2017年12月6日周三 17:23写道：

**Comment by lzghzr** [comment]
恩，已经改好了，因为改动太小就没加版本号

Vector000 <notifications@github.com> 于 2017年12月6日周三 22:02写道：
