### ISSUE TITLE
应援团签到错误

### ISSUE THREAD

**Issue by dawnspace** [lzghzr/bilive_client#34]
![image](https://user-images.githubusercontent.com/24506421/33703193-167adc0c-db62-11e7-84ff-c6b9361e775a.png)

**Comment by lzghzr** [comment]
获取列表有些问题，正在解决

dawnspace <notifications@github.com> 于 2017年12月7日周四 15:20写道：

**Comment by lzghzr** [comment]
已修复

**Comment by Fireblossom** [comment]
Dec 07 2017 22:34:29 : dx 日常活动 签名校验错误

大佬~请问这个是什么问题

**Comment by lzghzr** [comment]
@Fireblossom 更新一下cookie
