### ISSUE TITLE
今天更新之后出现应援团错误跟日常错误

### ISSUE THREAD

**Issue by zxc110123** [lzghzr/bilive_client#36]
Dec 08 2017 01:00:55 : 1 应援团签到 获取应援团列表失败 { code: 0, msg: '', message: '', data: { list: [] } }
Dec 08 2017 01:00:55 : 3 日常活动 签名校验错误
Dec 08 2017 01:00:55 : 2 日常活动 签名校验错误
Dec 08 2017 01:00:55 : 3 每日签到 已签到
Dec 08 2017 01:00:55 : 2 应援团签到 获取应援团列表失败 { code: 0, msg: '', message: '', data: { list: [] } }
是什么情况？

**Comment by lzghzr** [comment]
日常错误更新过cookie就好了，应援团错误是因为没有加入应援团
>data: { list: [] }

表示应援团列表是空的
