### ISSUE TITLE
火力票抽奖数量问题

### ISSUE THREAD

**Issue by catbule** [lzghzr/bilive_client#37]
这个是领取延迟决定的还是有别的方式可以领到？

**Comment by Fireblossom** [comment]
貌似是前100有火力票。确实是延迟决定的。

**Comment by lzghzr** [comment]
不是抽奖吗，我又不是B站的，我哪知道(～﹃～)~zZ

**Comment by Fireblossom** [comment]
前100有1个火力票，抽1个欧洲人50火力票，其他人都是1根辣条酱紫_(:з」∠)_

**Comment by lzghzr** [comment]
@Fireblossom 那就没办法了，脚本用的人多了自然不好抢

**Comment by dawnspace** [comment]
前一百指的是手机端的抽奖，大佬的软件应该是只抽pc端的，其实一次高能能抽两次的，手机端和pc端各一次。

**Comment by lzghzr** [comment]
@dawnspace 这几天一直有人说手机端可以抽奖，不过我是真没看到
如果像节奏风暴那样需要蹲点的话就不用告诉我了

**Comment by dawnspace** [comment]
和节奏风暴不一样的，在app端直播间半屏幕挂着时，如果有高能抽奖，会在弹幕聊天区的顶端有通知，点进去可以参与抽奖。应该和pc端的原理差不多

**Comment by dawnspace** [comment]
![image](https://user-images.githubusercontent.com/24506421/33761074-e0fae95a-dc42-11e7-8947-b2a1724dc4f3.png)

**Comment by lzghzr** [comment]
@dawnspace 好，我留意一下
