### ISSUE TITLE
作者你好~

### ISSUE THREAD

**Issue by yswcdmm** [lzghzr/bilive_client#38]
作者你的挂机很好用，我想问下你有群么？很多人想反应或者提交意见都无处可寻~

**Comment by lzghzr** [comment]
没有，因为嫌麻烦，不过确实有人因为一点小白问题就开issue，要不我弄个意见反馈的吧

yswcdmm <notifications@github.com> 于 2017年12月9日周六 10:09写道：

**Comment by lzghzr** [comment]
小问题可以到这里 #39
