### ISSUE TITLE
意见反馈及常见问题整理

### ISSUE THREAD

**Issue by lzghzr** [lzghzr/bilive_client#39]
1. 下载以后无法运行 #8 #16 #24\
不懂得nodejs以及npm的, 到[releases](https://github.com/lzghzr/bilive_client/releases/)下载编译好的版本\
按照[README](https://github.com/lzghzr/bilive_client/blob/master/README.md)上的操作一步一步完成
2. 需要在其他平台运行 #1 #28\
因为我只在Windows和Debian上测试过, 对于其他没有root权限的云平台不是很了解\
建议在[百度](https://www.baidu.com/)或者[谷歌](https://www.google.com/)搜索此平台nodejs的搭建步骤, 以及ip和端口绑定的方法
3. 因为版本更新导致新版无法使用 #20 #26 #31\
因为一直跟着nodejs的LTS版本更新, 当nodejs改动较大时, 之前引用的模块会失效, 此时只要重新安装新版nodejs以及npm install即可
4. 因为版本更新导致报错 #12 #34 #36\
当有一些新的点子但是受限于之前的配置文件时就会调整结构导致不可用或者报错\
在更新中没有明确说明需要重新配置的, 一般会在下一个签到周期(8小时)自动修复\
有明确说明需要重新配置, 又对json不熟的, 不要尝试直接修改文件
5. 因为B站改版或者B站服务器爆炸而无法挂机 #13 #27 #29 #33\
服务器爆炸这个我也没办法\
如果是改版的话可以在下面告知, 感兴趣的也可以提一个PR, 我也在努力的朝app方面迁移, 毕竟app为了兼容改动不会太大也不会太频繁
6. 需要新功能 #30 #37\
我认为有必要而且能做到的, 我会努力去做, 当然能赏个PR更好了\
要说一下我并不是程序员, 也完全不懂编程, 做这个东西只是兴趣而已

其他小问题, 认为几句话就可以说清的在下面反馈即可\
觉得问题很复杂而上面也没有解决方法的, 欢迎提issue, 我也可以为上面的内容做补充

**Comment by JerryRich** [comment]
现在一关闭chrome就显示连接已断开，可是chrome还挺占内存的，有没有什么方法可以在关掉chrome后也能保持连接啊作者大大

**Comment by lzghzr** [comment]
@JerryRich 没有影响，这个提示只是告诉你有人登录了系统然后又退出了，如果放在服务器上发现有异常就需要改密码了，本地用户不用理会

**Comment by brina60602** [comment]
这是不是要改dns才行？我插有线到路由_(:3」∠)_
还有 获得辣条X1 跟 获得 1 个辣条 有差别么？
![image](https://user-images.githubusercontent.com/15816106/33811046-4d63c1d2-de48-11e7-9edf-002bc12f35e9.png)

.

**Comment by lzghzr** [comment]
@brina60602 监听服务器已经关闭，设置里删除服务器地址即可。1个辣条和辣条x1加起来是两个，前者是PC端后者是app，一次火力全开可以抽两次

brina60602 <notifications@github.com> 于 2017年12月11日周一 08:03写道：

**Comment by Fireblossom** [comment]
大佬发个release呗~

**Comment by lzghzr** [comment]
@Fireblossom 没啥实质性的更新，而且还有一处已知bug
虽然会错过一些抽奖，不过无所谓啦，礼物已经够开车好几次了

**Comment by jdjingdian** [comment]
@lzghzr @Fireblossom 想尝试新功能自己编译来玩玩但是不太懂，装了typescipt，大佬能讲讲下载源码编译的大概步骤吗？下载有点迷糊

**Comment by zanewayne78** [comment]
dns缓存看来不能设置太长时间,解析到的ip晚上直播间服务器崩了,我还以为B站又出事了.
看来也能是上次B站直播全面崩溃后增加了备用的?

**Comment by Fireblossom** [comment]
@jdjingdian 建议等大佬发release，因为删了节奏风暴代码现在设置项里有几个undefined等着删掉，还有已知BUG等着修。
想尝鲜的话我在这说一下我怎么弄的：

1. `npm install -g typescript`
2. clone代码到本地
3. `cd`到目录
4. ·npm install·
5. `tsc`
6. 有个opinion文件夹，把之前的json丢进去
7. `npm start`测试了一下能用打包丢进服务器完事。

**Comment by jdjingdian** [comment]
@Fireblossom 谢谢，npm start没问题，但是我当我用pm2来启动app.js时就会出错，不知道为什么

**Comment by zanewayne78** [comment]
错误就把错误日志发出来,你这么说谁知道 @jdjingdian 新版已经更新了,不会就用编译好的

**Comment by lzghzr** [comment]
@jdjingdian 因为自己编译以后运行npm start和node app.js配置文件存储位置不同
是为了避免运行npm run clean不小心清掉个人设置

jdjingdian <notifications@github.com> 于 2017年12月18日周一 17:32写道：

**Comment by Fireblossom** [comment]
@lzghzr 刚发现1.2.6有BUG，小电视会卡死。

**Comment by lzghzr** [comment]
@Fireblossom emmmmm 我注意一下

**Comment by Fireblossom** [comment]
@lzghzr 我这边看到的情况是检测到小电视，然后就很久卡住不动，我试图Ctrl+C退出程序然后刚才小电视的领取成功信息就弹出来了，这期间设置界面都是连不上的，貌似是阻塞了。

**Comment by lzghzr** [comment]
@Fireblossom
这种情况在Windows有出现过，不止这个程序，其他依赖控制台输出的也有，应该是个系统bug，敲一下空格就好了，有时间我研究一下怎么避免

Fireblossom <notifications@github.com> 于 2017年12月18日周一 21:46写道：

**Comment by Fireblossom** [comment]
@lzghzr 我明白了，非常感谢。

**Comment by youth1996** [comment]
建议：自动送礼可以在设置账户的那个网址界面加一个 点击按钮，点击以后自动送礼。

**Comment by lzghzr** [comment]
@youth1996 打算下次和签到一起，13：30算特殊时间再送一次

youth1996 <notifications@github.com> 于 2017年12月19日周二 00:43写道：

**Comment by youth1996** [comment]
![image](https://user-images.githubusercontent.com/32319709/34157224-abdd5066-e4fb-11e7-9cc0-cd6f750d641f.png)
发现监控有些抽奖还是会漏掉

**Comment by lzghzr** [comment]
@youth1996 问了一下其他人，这个也漏掉了，事实上我也不知道为什么( ఠൠఠ )

**Comment by youth1996** [comment]
@lzghzr 嗯，我也再看看

**Comment by ccgeass** [comment]
@lzghzr 我最新版本报错


 Error: Cannot find module '/data/data/com.termux/files/home/blbl/build/app.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bilive_client@1.2.6 start: `node build/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bilive_client@1.2.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2017-12-20T10_47_46_853Z-debug.log
$

**Comment by lzghzr** [comment]
@ccgeass 你想在Android上运行的话需要自己编译
1. git clone https://github.com/lzghzr/bilive_client.git
2. cd bilive_client
3. npm install
4. npm run build
5. npm start

ccgeass <notifications@github.com> 于 2017年12月20日周三 18:51写道：

**Comment by zanewayne78** [comment]
又学到一招,不用一直开着电脑

**Comment by ccgeass** [comment]
@lzghzr ,感谢大佬回复。

**Comment by zanewayne78** [comment]
windows自动送礼失败
  ```
自动送礼 向房间 115 赠送 3 个亿圆 失败 { code: 200024, msg: '系统错误(569)', message: '系统错 误(569)', data: [] }
  自动送礼 向房间 115 赠送 7 个辣条 失败 { code: 200024, msg: '系统错误(569)', message: '系统错 误(569)', data: [] }
```

**Comment by lzghzr** [comment]
@zanewayne78 不支持短号，115原始房间号为1016

**Comment by zanewayne78** [comment]
原来如此,感谢

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: lzghzr <notifications@github.com>
发送时间: Saturday, December 23, 2017 1:53:12 PM
收件人: lzghzr/bilive_client
抄送: root; Mention
主题: Re: [lzghzr/bilive_client] 意见反馈及常见问题整理 (#39)


@zanewayne78<https://github.com/zanewayne78> 不支持短号，115原始房间号为1016

―

**Comment by 523860169** [comment]
原始房间号直接看直播间网址那个数字就是吗？

**Comment by LMM2860659395** [comment]
允许我问一个比较入门的问题，可以在树莓派上使用么？

**Comment by AdiEcho** [comment]
大佬能不能加一个每天把银瓜子换硬币的功能呀？

**Comment by RhythmNz** [comment]
请问这个有自动获取经验的功能嘛
以及那个设置页面是开源的嘛 如果不开源
如何手动设置呢？

**Comment by lzghzr** [comment]
@RhythmNz
获取经验是强制开启的，设置界面也在GitHub上，而且也打包到releases里了，也可以手动更改options.json(运行一次以后自动生成)

RhythmNz <notifications@github.com> 于 2017年12月25日周一 14:42写道：

**Comment by lzghzr** [comment]
@LMM2860659395 大概是可以，毕竟安卓上都可以运行

李卓 <lzggzr@gmail.com> 于 2017年12月25日周一 15:49写道：

**Comment by lzghzr** [comment]
@AdiEcho 700瓜子换1硬币还是挺亏的吧，而且每天就一个，我考虑一下

李卓 <lzggzr@gmail.com> 于 2017年12月25日周一 15:50写道：

**Comment by Dawnnnnnn** [comment]
@lzghzr 提供一个硬币换瓜子的接口  https://live.bilibili.com/exchange/coin2silver

**Comment by Dawnnnnnn** [comment]
@lzghzr 提供一个硬币换瓜子的接口 https://live.bilibili.com/exchange/coin2silver ，1硬币1000瓜子的旧版接口，来回换还是挺划算的23333    payload = {'coin':num}  post上去coin值就可以了

**Comment by lzghzr** [comment]
@Dawnspace 居然还有这种操作的(# ﾟДﾟ)

Dawnspace <notifications@github.com> 于 2017年12月25日周一 15:55写道：

**Comment by mscststs** [comment]
当我修改了Tools.ts以后，清理工作目录之后发现用npm install 和npm start中间必须加上npm run-script build，否则就会出错…是不是哪里不太对……

**Comment by LeecGitHub** [comment]
请问，这是出什么问题了？
![1](https://user-images.githubusercontent.com/26239550/34341563-cf1916c2-e9d4-11e7-86aa-f7e2ce24ee21.png)

**Comment by LeecGitHub** [comment]
已解决，是Node.js卸载未完全

**Comment by lzghzr** [comment]
@LeecGitHub 因为触发了验证码，而程序还没有显示验证码的功能，所以就登录失败了。一般过一段时间就好了

LeecGitHub <notifications@github.com> 于 2017年12月26日周二 09:00写道：

**Comment by lzghzr** [comment]
@youth1996 一天一次，但是应援团签到好像是24小时冷却，并不是按照自然天的，我也有几次没签上

youth1996 <notifications@github.com> 于 2017年12月26日周二 16:24写道：

**Comment by youth1996** [comment]
@lzghzr 建议可以12小时检查一次，因为一直开个这个检查不到，或许只是差十来分钟，然后就等下一天检查了，比较浪费，或是怎么说。

**Comment by codeisjobs** [comment]
大佬，我想问下，我在服务器上挂着，但是现在貌似每隔一天就会断掉，终端上不显示断开链接啥的信息，但是最后一行的时间一般都不和当前时间一样，断开之后的时间内礼物啥的也是不会变化的，所以能确定是断掉了，所以想问下有啥办法能一直保持链接吗，我的云服务器一直是开机的……不关机，就挂这终端，没有其他干扰的

**Comment by lzghzr** [comment]
@codeisjobs 暂时没发现这个问题，断掉以后还会签到吗？还是只有抽奖没有了

codeisjobs <notifications@github.com> 于 2017年12月27日周三 19:06写道：

**Comment by codeisjobs** [comment]
有时候是断的那刻是签到  有时候是抽奖

**Comment by LeecGitHub** [comment]
作者好，分支利用CDN规避ip限制可不可以出一个编译好的版本？

**Comment by sxinxins** [comment]
本人小白，想问下作者大大：关于【获取经验是强制开启的，设置界面也在GitHub上，而且也打包到releases里了，也可以手动更改options.json(运行一次以后自动生成)】
![n i6 8wr_n9 5v b 2 rj](https://user-images.githubusercontent.com/30524883/34398705-e9327b82-ebbb-11e7-83e8-9a13d17a893a.png)
设置界面哪个是啊？或者options.json怎么更改呢？

**Comment by lzghzr** [comment]
@LeecGitHub 弄好以后会合并到主分支，之后再编译。因为现在还是有些问题，对于网络不好的用户可能程序都无法运行

**Comment by qq270755744** [comment]
![2017-12-28_154116](https://user-images.githubusercontent.com/10820135/34403856-c71dd382-ebe5-11e7-9400-b1e5ddad63ff.jpg)怎么抓取b站cookie啊，一打开开关就显示失效

**Comment by S-H-Y-GitHub** [comment]
的确会无提示的断掉，我也出现了这个问题。3号直播间有个机器人记录了抽奖信息，可以据此发现是程序断掉了而不是没人送小电视。在Android端和Windows端都有这样的问题，出现频率很高，正常工作几十分钟（似那时正好也是一段时间没有人送出礼物，取样太少，触发条件还不明确）之后就会失效。重启进程偶尔可以解决，多数时候还是不行（似乎也是正好开始的时候没人送礼，过了一会有人送礼也领不了）

**Comment by sxinxins** [comment]
有一个意见或者说想法：
既然npm能显示抽奖结果，实现将小电视抽奖的非辣条结果（包括时间，道具类型和房间号之类）写入记事本。
或者简单一些，把npm里显示的所有内容自动存入记事本。
可以做到吗？方便做到吗？就是这个想法没太大意义

**Comment by lzghzr** [comment]
@S-H-Y-GitHub 了解了，我会观察一下是B站弹幕服务器不返回消息还是程序挂掉了

**Comment by lzghzr** [comment]
@sxinxins 类似统计的功能我不是很想做，毕竟这个程序只是自用的，每天打开包裹看看就行了，不推荐代挂

**Comment by youth1996** [comment]
楼主，据我观察，应援团签到也不是你说的上次的24小时以后更新，大概是下午两点更新，然后他们所说的连不上的问题，应该是挂了多账户，然后抽奖太多被封ip了，可以让他们在软件挂的时候自己打开浏览器看看。

**Comment by codeisjobs** [comment]
@youth1996 并不是 ，我的账号就一个，终端里也就挂着那一个账号……不存在多账户的情况……

**Comment by S-H-Y-GitHub** [comment]
@youth1996 我在浏览器里可以正常收到抽奖信息，点击进入抽奖房间也可以正常加入抽奖

**Comment by S-H-Y-GitHub** [comment]
@youth1996 我在浏览器里可以正常收到抽奖信息，点击进入抽奖房间也可以正常加入抽奖

**Comment by youth1996** [comment]
@codeisjobs ，@SHY-GitHub 那这样的话，也不是很清楚， 多账号并不是肯定多账号，有事连续抽奖次数过多被封ip是存在的，SHY-GitHub 你在浏览器可以正常抽奖说明不是被封ip了。

**Comment by lzghzr** [comment]
@S-H-Y-GitHub 原因找到了，因为socket和ws协议写在了一起，逻辑上出现了错误，断线以后不会自动重连，所以才会监听不到。居然一直没发现这个问题≡(▔﹏▔)≡

**Comment by codeisjobs** [comment]
@lzghzr   能改就好……哈哈

**Comment by lzghzr** [comment]
1.2.7版设置网页关闭以后控制台会报错属正常现象，倒是以前不报错有些不正常

**Comment by sxinxins** [comment]
更新到新版本可以直接覆盖老版本吗？还是要把老版本删除再重新设置？刚刚覆盖完重开npm和网页，关网页没有报错，和之前一样只是提示已断开。

**Comment by lzghzr** [comment]
@sxinxins 直接覆盖就可用
运行npm install安装新版本ws就会报错，不过我已经修好了

**Comment by youth1996** [comment]
可用ip数量为43是啥意思，一秒以内43次响应不会被封ip？

**Comment by qq270755744** [comment]
需要一直打开直播间才能领礼物吗

**Comment by lzghzr** [comment]
@qq270755744 当然不需要，只要保持命令行开启就行了

qq270755744 <notifications@github.com> 于 2017年12月30日周六 12:48写道：

**Comment by lzghzr** [comment]
qq270755744:
> 需要一直打开直播间才能领礼物吗

owner:
> 当然不需要，只要保持命令行开启就行了

**Comment by sxinxins** [comment]
![3l1 wu t2 1a dlxf i](https://user-images.githubusercontent.com/30524883/34462350-2773ea66-ee7d-11e7-88c3-21e83642287c.png)
这种情况是为什么啊？装了node-v8.9.1-x86.msi。版本装错了还是路径问题还是什么原因？

**Comment by S-H-Y-GitHub** [comment]
作者大大有没有直播间呀，辣条太多了去支持一下

**Comment by AdiEcho** [comment]
@sxinxins 你要设置一下path
顺便再次请求一下作者大大 @lzghzr 制作一下银瓜子换硬币，因为挂机以后每日的礼物足够赠送给喜欢的主播，存下来的银瓜子与每天获得的礼物相比相形见绌，但是换成硬币的话可以给喜欢的视频投币，能给自己加主站的经验+给UP主加硬币，还是希望作者能加一下这个功能，谢谢(๑•ᴗ•๑)

**Comment by lzghzr** [comment]
@S-H-Y-GitHub 没有，实在多的话就送三号直播间吧

**Comment by youyoudeminger** [comment]
想请问一下作者自动送礼如何使用

**Comment by jdjingdian** [comment]
看了一下自动送礼好像是每天两根辣条，比较好奇的是快要到期的辣条是否会全部送完，还是说如果不手动送完就会失效？

**Comment by lzghzr** [comment]
@jdjingdian 只送不足24小时的，每天00:30，08:30，13:30，16:30都会送一次
而且不限数量，如果这次活动的辣条你没送多少，又恰好开着自动送礼，就会在到期前一天的16:30全部送出，可能直接触发频道广播

**Comment by jdjingdian** [comment]
@lzghzr 了解了，谢谢大佬

**Comment by FThePatriarchy** [comment]
![image](https://user-images.githubusercontent.com/35087852/34548875-14181466-f0ca-11e7-9c54-81b752640384.png)
之后一直是“Jan 03 2018 21:08:19 : user Token已失效
Jan 03 2018 21:08:21 : user Token已更新
Jan 03 2018 21:08:21 : user Cookie已失效”
请问这个是怎么回事啊？之前在自家还好，今天到学校后出现了问题，是因为网络吗

**Comment by FThePatriarchy** [comment]
![image](https://user-images.githubusercontent.com/35087852/34550834-9d2c2ad0-f0d9-11e7-936d-89a760cd85cd.png)
发现了这个情况，之前在家没有发生过。现在到学校出现的。
请问有什么办法吗

**Comment by sxinxins** [comment]
@FThePatriarchy  看着想是被封IP了。看你两个截图的时间，大概是封至少一天的节奏。

**Comment by lzghzr** [comment]
@FThePatriarchy @sxinxins 应该只是网络的原因，被封会返回403
@FThePatriarchy 你可以试一下能不能打开直播间，直播间打开以后是否有弹幕

**Comment by FThePatriarchy** [comment]
能够打开直播间，有弹幕，而且能领便当
可能是网络原因吧，下个周学校正式开学，会把wifi从公开的转成私人的。到时候再试一下。
谢谢回复！

**Comment by sxinxins** [comment]
@FThePatriarchy  也可以连手机热点先试试？

**Comment by fs779** [comment]
这个整么绑定api的IP哇？？？？

**Comment by WeissRu** [comment]
打不开设置页面，但是通过改json能正常使用。
系统版本 Windows insider preview 17063 
浏览器Microsoft Edge 42.17063.1000

**Comment by lzghzr** [comment]
@WeissRu 不支持edge

WeissRu <notifications@github.com> 于 2018年1月6日周六 12:30写道：

**Comment by fs779** [comment]
想要一个自动换硬币自动分享视屏功能哇qwq

**Comment by skybiu** [comment]
@lzghzr 大大，打开之后就一直是这样的。这里只显示了有房间抽奖，没有我参加抽奖的？是需要登陆吗？
![image](https://user-images.githubusercontent.com/20654042/34640209-512a52fe-f329-11e7-8f0c-dbfb538601af.png)

**Comment by lzghzr** [comment]
@houhou 碰巧打开的时候有人送礼物，没参与正常。还有就是需要登录

houhou <notifications@github.com> 于 2018年1月6日周六 21:35写道：

**Comment by skybiu** [comment]
@lzghzr 我要怎么登录呢？我在浏览器里面有登录的呀

**Comment by lzghzr** [comment]
@houhou 可以打开目录里的index.html，也可以去
http://lzghzr.github.io/bilive_client_view/index.html

houhou <notifications@github.com> 于 2018年1月6日周六 21:39写道：

**Comment by skybiu** [comment]
@lzghzr 嗯嗯，谢谢大大，我刚刚找到了

**Comment by jdjingdian** [comment]
大佬辛苦了，这段时间高产，注意身体 @lzghzr

**Comment by lovezm** [comment]
@lzghzr dalao  我现在运行app.js  返回的日志文件 是错误页面的源码，是不是被墙了啊

**Comment by jdjingdian** [comment]
1.3.1版本可用IP数量为0，并且监听不到礼物信息
<br/>
<img src=http://chuantu.biz/t6/200/1515394168x-1404775429.png />

**Comment by lovezm** [comment]
那咋整啊 我也是这样的

**Comment by jdjingdian** [comment]
先退回先前版本吧，不过先前版本最近也经常连不上监听服务器
《br/》
<img src=http://chuantu.biz/t6/200/1515394389x-1566688536.png />

**Comment by youth1996** [comment]
0就是被封ip一个小时， 等一个小时就可以了

**Comment by lovezm** [comment]
原来如此，谢谢了。

**Comment by lzghzr** [comment]
@lovezm @jdjingdian 看不到具体的状态码(页面源码上可以看到)，如果是403的话就应该是被B站封掉了，其他的就是网络波动啦

**Comment by lovezm** [comment]
@lzghzr 就是403 阿西吧。。。。挂在阿里云的。。。。

**Comment by jdjingdian** [comment]
哈哈哈那正好休息一下，我用pm2托管程序，刚刚一看日志文件都11mb了

**Comment by lovezm** [comment]
封了！还会解封吗！

**Comment by jdjingdian** [comment]
@lovezm 楼上已经说了等一个小时就好了

**Comment by lovezm** [comment]
我还以为服务期ip就这样被B战弄死了。，

**Comment by lovezm** [comment]
已经开放了10080端口 本地还是链接失败..之前用ssh转发了10080 本来是可以的后来由于被封了 重启了一下服务期现在不知道为啥一直无法转发陈宫了

**Comment by lovezm** [comment]
bind: Cannot assign requested address
channel_setup_fwd_listener_tcpip: cannot listen to port: 10080
Could not request local forwarding.

**Comment by lovezm** [comment]
如何是好啊 有没有大佬教一下  linux上搭建了 也一直在运行 就是我本地没办法进后台设置 这样的问题求一个解决方案。。。
![image](https://user-images.githubusercontent.com/10624938/34668804-ec70b0c4-f4a9-11e7-83e9-337f8b32135a.png)

![image](https://user-images.githubusercontent.com/10624938/34668781-d1aa99d0-f4a9-11e7-8a26-c0987d4d2b4d.png)

**Comment by AdiEcho** [comment]
@lovezm 在自己的电脑上配置好，然后把文件夹里的options文件扔到VPS里就行了

**Comment by lovezm** [comment]
这样我也知道 但是每次都要上传呀

**Comment by AdiEcho** [comment]
@lovezm 你要经常加人吗？不变动的话直接npm start就行了

**Comment by lovezm** [comment]
@AdiEcho 小号有点多 需要家人。我在win跑的时候是挺简单的可是win快到期了 就放到啊linux了 奈何一直搞不定访问的问题

**Comment by AdiEcho** [comment]
@lovezm 小号多就一次性加啊，也用不着一会加一次吧...而且你可以在自己电脑上加好大概那个数量的空帐号后扔到VPS里，以后加帐号直接VIM就行了

**Comment by lovezm** [comment]
也只能这样了 我是想通过网页访问更方便的 既然难搞就只能用手动的了

**Comment by lovezm** [comment]
建议给每个账号下面增加一个能设置代理的功能 我一个朋友的程序有这个功能  很大几率能解决B站banip的问题

**Comment by jdjingdian** [comment]
水一条评论，感慨一下
<br/>
活动一结束，瞬间捡不到辣条了。BLS活动时一个晚上几千根辣条，现在，一整天才一百多条
<br/>坐等b站开启下次土豪竞争活动

**Comment by lovelyyoshino** [comment]
这个可以抢风暴了嘛

**Comment by lzghzr** [comment]
@lovelyyoshino 不提供抢节奏风暴功能

**Comment by Franinc** [comment]
宝箱领瓜子好像只能领三轮，会员（包括签到送的）实际能领五轮每天

**Comment by lzghzr** [comment]
@Franinc 可以领完啊
![chrome_2018-01-12_17-37-30](https://user-images.githubusercontent.com/13391314/34868638-6506009e-f7bf-11e7-88d3-45519a4f2f36.png)

**Comment by Franinc** [comment]
@lzghzr 刚才重开了一次就可以领了……之前15点时看一直没领第三轮9分钟的就重开了一次，然后到17点发现第四轮还是一个没领

**Comment by Fireblossom** [comment]
![qq 20180112191212](https://user-images.githubusercontent.com/16226671/34872684-d6814b04-f7cc-11e7-888d-cc48f84cbb93.png)
我这里又出现了双端观看任务不完成的问题=。=

**Comment by lzghzr** [comment]
@Franinc 不知道现在什么情况，很久以前如果进入房间会重置宝箱的冷却时间
所以，如果你在其他地方也挂机，或者一直在刷新房间的话可能会一直无法完成

**Comment by selfler** [comment]
sendGiftRoom参数错误
自动送礼怎么不行~~

**Comment by zanewayne78** [comment]
@selfler 更新，以前的房间号不能用3位以下的短号

**Comment by selfler** [comment]
下的是release最新的了。。。而且填的也不是短号呢

**Comment by zanewayne78** [comment]
不行的话就在options.json里面改吧
"sendGiftRoom":房间号（没有引号）

**Comment by selfler** [comment]
好的 👌搞定

**Comment by jdjingdian** [comment]
新活动开启后收到错误提示</br>
`TimeoutOverflowWarning: 1516265800000 does not fit into a 32-bit signed integer.</br>Timeout duration was set to 1.
`
但好像没有影响抽奖结果

**Comment by lzghzr** [comment]
新活动客户端抽奖有人反馈说 显示小红包实际上是小灯笼 并不是bug

**Comment by fs779** [comment]
就是啊我也发现了，

**Comment by fs779** [comment]
大佬似乎有必要弄个自动兑换功能我。。。瞬间就没了5555

**Comment by lzghzr** [comment]
@fs779 我还没搞懂怎么玩……等我搞明白了再看看有没有必要
但是估计不会做这个功能

**Comment by alhricke** [comment]
`(node:2731) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: fs.copyFileSync is not a function
(node:2731) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
@lzghzr 被水淹没，不知所措

**Comment by lzghzr** [comment]
@alhricke node版本需大于8.5.0

**Comment by QHDS** [comment]
@lzghzr 具体这个抢礼物有这个，你看下

http://bilibili.101100.top/b/

**Comment by lzghzr** [comment]
@QHDS 抢礼物功能我在 [#54](https://github.com/lzghzr/bilive_client/issues/54#issuecomment-359124111)已经说过了，不会做的

**Comment by QHDS** [comment]
@lzghzr   抱歉，是我没注意

**Comment by QHDS** [comment]
@lovezm
看到你这个，我是不是应该悄咪咪的更新一下前端
突然自卑

**Comment by brina60602** [comment]
@lzghzr 這次活動不是到28號嗎...我的燈籠全被自動送出了_(:3」∠)_
還有一個幾天前換到的新春抽奖也被送了...(´；ω；`)

**Comment by lzghzr** [comment]
@brina60602 是不足24小时的礼物，活动礼物已在2018.02.27 16:00不足24小时，所以会被送出

**Comment by brina60602** [comment]
@lzghzr 能改成當天下午嗎? _（：3」∠）_

**Comment by lzghzr** [comment]
@brina60602 不会，因为这个功能是为长时间无法管理或者懒得管理B站账号的人准备的，所以优先保证礼物可用被送出，如果每天都会登录B站的话不建议开启此功能
