### ISSUE TITLE
请教下大佬，有个设置没起作用

### ISSUE THREAD

**Issue by diaosimiao** [lzghzr/bilive_client#4]
看了大佬的代码好久，不知道怎么调整节奏风暴设置起作用。
我给大佬这个邮箱bbcallen@gmail.com发了好几份邮件学习着解决自己遇到的难题。基本解决了。
深感程序员真是辛苦，感谢您提供的项目造福小白苦手。鞠躬。

**Comment by lzghzr** [comment]
@diaosimiao 因为节奏风暴有数量限制，为了防止拼网速抢亿圆的情况发生，该功能不对外开放。实际上现在的情况是有专门的工作室在抢亿圆，我自己和B站服务器延迟才6ms，都不能100%抢到

**Comment by lzghzr** [comment]
以及bbcallen@gmail.com这个邮箱不是我的，不要感谢错人了
