### ISSUE TITLE
活动高能没触发抽奖（bilibili live-star活动）

### ISSUE THREAD

**Issue by tzhongyan** [lzghzr/bilive_client#41]
如题，在各位巨佬各显神通的情况下，我发现如果直播间的抽奖高能是被“嗨翻全场”道具触发，挂机系统就不会触发抽奖；225x哔哩星的就没问题

我怀疑是`giftID`返值不同的原因，尝试过翻看数据，但我找不到有关于`giftID`的信息，希望作者大佬可以注意一下，或者给介绍下是哪个GET/POST资源的返值呢？

**Comment by lzghzr** [comment]
嗯，确实会这样，我想个办法
