### ISSUE TITLE
关于账号的疑问

### ISSUE THREAD

**Issue by insulatedV5** [lzghzr/bilive_client#42]
小白想请教一下 npm start后登陆的账号是自己浏览器上登陆的账号吧
我想尝试2个账号登陆抽奖 可以么
另外 这个有抽奖反馈么 
![50mti_gaqfnuzbggm6b44 m](https://user-images.githubusercontent.com/34591039/34196481-4045d9f2-e59d-11e7-8907-4249402baea7.png)

**Comment by dawnspace** [comment]
网页设置里有添加，可以添加账号，但是....你应该先解决你的登陆问题....你根本都没登陆成功.......正常的话会显示抽奖结果的。 @insulatedV5

**Comment by insulatedV5** [comment]
原来如此  请问该如何登陆

**Comment by insulatedV5** [comment]
已解决

**Comment by mohongchen** [comment]
Dec 29 2017 16:38:22 : ::1:3640 已连接
Dec 29 2017 16:40:37 : user1 Cookie已失效
Dec 29 2017 16:40:38 : user1 Token已失效
Dec 29 2017 16:40:38 : user1 Token更新失败 { ts: 1514536838, message: 'CAPTCHA is not match', code: -105 }
这种一直登不上怎么办？

**Comment by lzghzr** [comment]
@Lismore 验证码功能暂未实现

Lismore <notifications@github.com> 于 2017年12月29日周五 16:42写道：
