### ISSUE TITLE
大佬好，我在linux上搭建好了 ，设置进不去...

### ISSUE THREAD

**Issue by lovezm** [lzghzr/bilive_client#45]
我用ip:10080 链接失败 这样的问题咋解决啊  急急急 在线等

![image](https://user-images.githubusercontent.com/10624938/34658525-b5b18264-f46a-11e7-9b94-11a4a171e889.png)

**Comment by lzghzr** [comment]
可以参考以下方法
* 服务器有防火墙，需要打开10080端口
* 使用ssh tunnel转发10080端口到本地
* 在本地设置好后，把options文件夹上传到服务器

**Comment by lovezm** [comment]
好的。 话说 这个在linux上  要如何后台运行呢  ctrl+c就停止了吗  还是run以后可以直接关闭ssh连接

**Comment by lovezm** [comment]
我找到方法了 谢谢 终于可以在闲置的linux上跑点东西了！

**Comment by lzghzr** [comment]
你可以试试直接访问http://你的ip:10080 <http://xn--ip:10080-im2mi643a>
如果服务器没问题应该会302跳转到github.io

WangMuDu <notifications@github.com> 于 2018年1月8日周一 12:53写道：

**Comment by lovezm** [comment]
我访问没有跳转...是什么情况 10080端口我也是开的..

**Comment by lzghzr** [comment]
然后利用telnet之类的工具试一下端口是否可以访问。我估计是不行，程序也在后台跑，就是外网无法访问的话，也有可能是主机商有限制之类的

我自己的方案是

程序使用Unix sock(options.json里是支持设置的，而且优先级比端口高)

然后Nginx反代一下，顺便加个ssl

WangMuDu <notifications@github.com> 于 2018年1月8日周一 19:34写道：

**Comment by lovezm** [comment]
我刚才看了一下 貌似不会自己清空显示今日到期的辣条啊 我刚还手动清空了8个号的今天到期的辣条。。。

**Comment by tzhongyan** [comment]
那些辣条应该是清空之后的高能抢的，而程序只是在特定时间运行签到、清理包裹、检查宝箱…………所以下午2点活动结束之前的高能低保还是要注意下，可能需要手动送完

**Comment by lovezm** [comment]
一下午 8个号 每个都抢了2000的辣条  送死我了。。。

**Comment by lzghzr** [comment]
每天00:30 08:30 13:30 16:30都会自动送一次
如果想手动触发可以
网页设置里关闭开关，保存，再打开开关，再保存
或者直接重启

WangMuDu <notifications@github.com> 于 2018年1月9日周二 10:15写道：

**Comment by lovezm** [comment]
嗯 好的  还有辣条清空是啥时候啊

**Comment by lzghzr** [comment]
自动送礼的时候就会清空不足24小时的了，活动14:00结束，也就是说只会浪费13:30~14:00这段时间的辣条

**Comment by lovezm** [comment]
那就好 很高级啊

**Comment by lovezm** [comment]
B站有点炸啊 我三台机器轮着403....现在挂机 日志不跑 也不知道是不是也GG了

**Comment by lzghzr** [comment]
按理来说应该是不会因为访问过快触发403的
如果账号太多的话可以尝试将index.js Start()内的tools.testIP()前面加await，等待测试ip完成后再初始化用户

**Comment by lovezm** [comment]
好的，我3台一起运行 有没有影响啊 ，一样的用户配置。

**Comment by lovezm** [comment]
大佬的nodejs在哪学的 好想学一下啊

**Comment by lzghzr** [comment]
一切起源这个[帖子](http://tieba.baidu.com/p/4186718143)
有需求就有动力了
大概就是起初B站没关键词屏蔽，就自己百度代码做了一个（百度学JavaScript，主要JQuery）
然后既然屏蔽词有了就屏蔽特效（百度学CSS）
接着动歪脑筋想自动抽小电视 （继续百度学JavaScript）
B站出了节奏风暴，用浏览器监听实在是太浪费资源了，所以百度到一个叫Node.JS的东西，之前浏览器的代码改一改就能用（接触Node.JS)
为了可以其他人也可以用到，而且我还可以控制功能，就学了一下C/S，因为当时百度的资料都是node 0.10版的了，所以主要就是[stackoverflow](https://stackoverflow.com/)和[github](https://github.com/)抄代码，然后学习JavaScript语法[ECMAScript 6 入门](http://es6.ruanyifeng.com/)
最后为了方便设置就写了个网页 (百度学HTML)
就是这样……

**Comment by lovezm** [comment]
厉害啦 我就是学不下去 哎。

**Comment by diaosimiao** [comment]
萌萌哒的大佬历程 看完只有一个字 lz gh zr牛逼

**Comment by diaosimiao** [comment]
萌萌哒的大佬历程 看完只有一个字 lz gh zr牛逼！

**Comment by alhricke** [comment]
@lzghzr 你好，请问可以修改端口号嘛？

**Comment by lzghzr** [comment]
手动修改options.json
``` JavaScript
  "server": {
    "path": "", // 此处可以填写Unix Domain Socket, 并且优先级高于端口
    "hostname": "127.0.0.1",
    "port": 10080,
    "protocol": "admin"
  }
```

**Comment by alhricke** [comment]
@lzghzr 请问该如何设置呢？我配置好了，链接也跳转到了GitHub，但是无论怎么样都是链接失败，

**Comment by lzghzr** [comment]
@alhricke 可以看一眼控制台报错
