### ISSUE TITLE
请教树莓派的挂机问题

### ISSUE THREAD

**Issue by whychobits** [lzghzr/bilive_client#49]
大佬您好，我在win系统下可以正常使用您的程序，现在想在树莓派上运行，可以更加低耗稳定，不知您有没有相关教程，我始终无法成功，谢谢您！

**Comment by Fireblossom** [comment]
报啥错呀

**Comment by jdjingdian** [comment]
还真有人想这么干哈哈哈哈哈，你把报错信息贴上来才能帮你啊

**Comment by lzghzr** [comment]
并没有派……不过不也是Linux系统的嘛，应该没啥问题吧

**Comment by liansishen** [comment]
我挂在派上没有问题

**Comment by lovezm** [comment]
node.js 版本是啥? 低版本运行不了的。
