### ISSUE TITLE
活动又开始了

### ISSUE THREAD

**Issue by zanewayne78** [lzghzr/bilive_client#53]
https://live.bilibili.com/pages/1703/spring-2018.html
土豪大显身手的时候到了

**Comment by zanewayne78** [comment]
话说在线经验是不是要没了？
[公告](https://link.bilibili.com/p/eden/news#/newsdetail?id=459)
[公告更新](https://link.bilibili.com/p/eden/news#/newsdetail?id=458)

**Comment by jdjingdian** [comment]
1.经验改版暂时没开始执行
2.老爷用户不受影响
3.充钱吧哈哈哈哈或

**Comment by lzghzr** [comment]
嗯，正在测试，稍后更新

**Comment by zanewayne78** [comment]
@lzghzr 
我好像还没更新就能抽了
Jan 18 2018 16:13:36 : 房间 5096 开启了第 1 轮抽奖
Jan 18 2018 16:13:36 : 房间 5096 开启了第 1 轮客户端抽奖
Jan 18 2018 16:13:36 : 你 抽奖 1 获得小红包X1
Jan 18 2018 16:14:30 : 房间 64448 开启了第 2 轮抽奖
Jan 18 2018 16:14:30 : 房间 64448 开启了第 2 轮客户端抽奖
Jan 18 2018 16:14:30 : 你 抽奖 2 获得小红包X1
Jan 18 2018 16:15:07 : 你 抽奖 1 获得 1 个小红包
Jan 18 2018 16:16:03 : 你 抽奖 2 获得 1 个小红包
Jan 18 2018 16:21:43 : 房间 1365604 开启了第 3 轮抽奖
Jan 18 2018 16:21:43 : 房间 1365604 开启了第 3 轮客户端抽奖
Jan 18 2018 16:21:43 : 你 抽奖 3 获得小红包X1
Jan 18 2018 16:23:13 : 你 抽奖 3 获得 1 个小红包
Jan 18 2018 16:29:20 : 房间 3742025 开启了第 4 轮抽奖
Jan 18 2018 16:29:20 : 房间 3742025 开启了第 4 轮客户端抽奖
Jan 18 2018 16:29:20 : 你 抽奖 4 获得小红包X1
Jan 18 2018 16:29:23 : 房间 4641942 开启了第 5 轮抽奖
Jan 18 2018 16:29:23 : 房间 4641942 开启了第 5 轮客户端抽奖

**Comment by lzghzr** [comment]
@zanewayne78 嗯，但是B站改了参数，需要修改一下
