### ISSUE TITLE
关于双端任务无法完成

### ISSUE THREAD

**Issue by lzghzr** [lzghzr/bilive_client#59]
经观察未能完成双端任务的账号皆为
2018年02月07日，B站账号系统出错后未更新cookie的
手动清除cookie，关闭开关，再打开开关更新账号信息之后即可恢复正常

@lovezm @youyoudeminger @jdjingdian

**Comment by jdjingdian** [comment]
好的，谢谢大佬！

**Comment by lzghzr** [comment]
发现今天双端又无法完成了，在考虑是不是要加一个七天自动更新账号信息……

**Comment by diaosimiao** [comment]
汇报下 看了一眼heroku 无改一直运行26天 共2个号都双端完成了（2月1号稳定运行至现在）

**Comment by lv100** [comment]
Feb 27 2018 09:55:52 : 正在测试可用ip
Feb 27 2018 09:55:53 : 可用ip数量为 0
为啥没有了

**Comment by LeecGitHub** [comment]
@lzghzr 大佬发现个新问题，是不是因为没有活动抽奖，双端任务最近不完成啦（已清理cookie重新开关

**Comment by lovezm** [comment]
今天又没完成了。。

**Comment by lovezm** [comment]
B站改了的吧。

**Comment by lzghzr** [comment]
@lovezm [ASCII QR](http://www.asciiqr.com/)

**Comment by lovezm** [comment]
我一个朋友说B站API改了。他做的PHP版本的。

**Comment by lzghzr** [comment]
@lovezm 据我了解宝箱的改了，任务的没改
不过因为我用的宝箱api是客户端的，目前没什么影响

**Comment by sxinxins** [comment]
今天才发现双端没完成。重启有用吗，还是暂时只能手动完成任务

**Comment by sxinxins** [comment]
反馈一下，昨天npm没做双端任务，今天完成了

**Comment by lzghzr** [comment]
嗯，今天我再次观察到了无法做任务，但是可以参与小电视的情况，并且是明确提示未登录
大概是cookie和token过期时间不一致导致的……所以，不管了，每天刷新一下cookie吧

**Comment by lzghzr** [comment]
今天发现刷新cookie的api并不好用

**Comment by sxinxins** [comment]
嗯，今天双端任务完成了没领取

**Comment by lovezm** [comment]
怎么每天刷新cookie。。重启程序还是重新开关

**Comment by sxinxins** [comment]
@lovezm 重新开关就能刷新
另，今天双端任务中网页端没有完成

**Comment by lzghzr** [comment]
@lovezm 本来我是打算用这个api自动刷新的，结果昨天才发现这个api不好用，手动的话删除cookie，重新打开开关

**Comment by lzghzr** [comment]
嗯，好像B站又修好了这个api……
