### ISSUE TITLE
几个奇怪的报错

### ISSUE THREAD

**Issue by Naexen** [lzghzr/bilive_client#62]
偶尔就会断掉的抽奖 也不知道是不是我电脑休眠还是啥原因

**Comment by Naexen** [comment]
http://api.live.bilibili.com/gift/v2/smalltv/notice?roomid=1495752&raffleId=40200 { Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

**Comment by Naexen** [comment]
http://api.live.bilibili.com/gift/v2/smalltv/notice?roomid=867764&raffleId=40199 { Error: connect ETIMEDOUT 47.91.74.133:80
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '47.91.74.133',
  port: 80 }

**Comment by Naexen** [comment]
http://api.live.bilibili.com/mobile/freeSilverCurrentTask?access_key=82849753cf0670bc08d5e99c1bc69971&actionKey=appkey&appkey=1d8b6e7d45233436&build=5210000&mobi_app=android&platform=android&ts=1520757048&sign=5463a155ee6f8756ad82c979fcf691d0 { Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

**Comment by Naexen** [comment]
{ status: 2,
  error: Error: 心跳超时
    at Timeout._timeout.setTimeout [as _onTimeout] (C:\Users\qwq\Desktop\bilive_client\bilive\lib\dm_client.js:147:69)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) }

**Comment by Naexen** [comment]
顺便问一下账户信息都保存在哪个文件里面啊 我以前作死不知道挪那个文件就直接整个覆盖导致现在似乎会出现两个获得提醒 有时候似乎还会不显示xxx房间开启抽奖的提醒

**Comment by Naexen** [comment]
上面那几个报错都是经常出现的 我以前试着收集过报错 文本都200多k了

**Comment by Naexen** [comment]
嘛顺便问一下大家有没有什么好的挂机方法 我开着电脑太耗电了心疼qwq

**Comment by lzghzr** [comment]
报错都是网络超时，也就是为什么会漏掉抽奖的原因
心跳超时那个是和弹幕服务器断开了
账号信息在options/options.json

难道你是在国外吗，网络这么不稳定的

挂机的话可以买最近的腾讯云啊，除了挂B站还可以挂一大堆东西 [binux/qiandao](/binux/qiandao)

**Comment by ShmilyChen** [comment]
@lzghzr 大佬我在我的腾讯云上部署了https://github.com/binux/qiandao，但是我在运行./run.py
时报错Traceback (most recent call last):
  File "./run.py", line 42, in <module>
    PeriodicCallback(worker, config.check_task_loop, io_loop).start()
TypeError: __init__() takes exactly 3 arguments (4 given)
请问怎么解决啊

**Comment by lzghzr** [comment]
@ShmilyChen 你问作者呀，我又没用过

**Comment by Naexen** [comment]
有个新问题是我昨天晚上一个晚上都没刷新出抽奖信息。。也没啥报错之类的 最新版本

**Comment by Naexen** [comment]
最近挂的几个小号会出现没有抽上奖的情况 随机出现

**Comment by lovezm** [comment]
买个树莓派  省电。

**Comment by lzghzr** [comment]
@Naexen 所以你是什么网络呢？如果网络没问题的话可以把options.default.json里面的ip挑几个用，或者直接不用，完全靠本地DNS解析

**Comment by Naexen** [comment]
有没有新版本啊0A0更新癌有点按捺不住了

**Comment by Naexen** [comment]
我的网络是电信0A0目前这个情况比较少见了

**Comment by Naexen** [comment]
@lzghzr 我现在本地和服务器都只显示抽奖开启没有抽奖结果了。。辣条也没见增加。。能不能麻烦看看是什么情况啊qaq没有报错

**Comment by lzghzr** [comment]
看 #66 可能被封了
