### ISSUE TITLE
静态页面的一些优化建议

### ISSUE THREAD

**Issue by BugKun** [lzghzr/bilive_client#64]
建议优化本地服务器的跳转逻辑，应优先使用本地的静态页面，
然后控制台页面的链接地址用 location.host 的方式作为默认链接。

另外还有一个小小的建议，把静态页面的protocol的输入框改成 type="password" ，当然在输入框内加个显示或隐藏密码的开关就更好了。（这项建议对体验影响不大，忽略也行）

**Comment by lzghzr** [comment]
之所以跳转是为了可以实时更新静态页面（不过我会考虑移到其他地方，比如码云），本地文件直接双击就可以打开了，只是作为备用

protocol实际上是websocket的子协议，因为我还不完全了解ws，不知道是否可以跳过，所以不完全保证可以作为密码使用，自己实现一个密码功能的话又和现在的功能冲突

**Comment by BugKun** [comment]
因为我是挂在服务器上的，为了安全，我想设置一个密码，但是又懒得改页面，于是就自己修改options.json的protocol，当密码用。我自己用的是socket.io，没有设置过protocol。

**Comment by lzghzr** [comment]
我也是一样的用法，只不过放在nginx后面，加了tls

**Comment by BugKun** [comment]
我觉得你这里可以直接用protocol，当密码用。

**Comment by BugKun** [comment]
另外服务器设置跳转的话，能否这样设置，在跳转到静态页面是加个参数 
`"?from=" + req.headers.host `或`"#" + req.headers.host `
这样，然后静态页面用location.search或location.hash获取并作为默认链接的地址。

**Comment by lzghzr** [comment]
你是想说"记住密码"吗

**Comment by BugKun** [comment]
不是，我是说ws://localhost:10080这个地址，每次都要重新输入远程服务器的地址，可以做记住地址或者在服务器跳转时带服务器地址的参数，并在前端页面解析服务器的地址。

**Comment by BugKun** [comment]
本来想Fork帮你改前端页面的，可是前端页面没在你的项目中（只有发行版中有），所以还是你来改吧！

**Comment by BugKun** [comment]
protocol那里，我想加一个像密码那样的输入框，旁边有个选项，显示/隐藏输入，这样。
对应的是type=password/type=text

**Comment by lzghzr** [comment]
静态页面在github.io里，也欢迎PR

BugKun <notifications@github.com> 于 2018年3月24日周六 10:09写道：

**Comment by BugKun** [comment]
主要的问题是，我看不到你静态页面的项目，我不知道fork哪个项目，也pr不了。

**Comment by BugKun** [comment]
还是说我直接把改完后的直接pr到这个项目里？

**Comment by lzghzr** [comment]
https://github.com/lzghzr/lzghzr.github.io

BugKun <notifications@github.com> 于 2018年3月24日周六 13:06写道：

**Comment by shugen002** [comment]
我个人建议把这个静态页面剥离出来单独一个仓库吧，不要都放在github.io，fork别人的github.io有点尬。。。。做成类似这样 [[esterTion/estertion.github.io](https://github.com/esterTion/estertion.github.io)] -   [estertion.github.io](https://github.com/esterTion/estertion.github.io) 
与 [[esterTion/BiliPlus-Log-Data](https://github.com/esterTion/BiliPlus-Log-Data)] - [BiliPlus-Log-Data](https://estertion.github.io/BiliPlus-Log-Data/) 的关系

**Comment by shugen002** [comment]
既然都搬进来了，那就接着提建议吧
1 加多个启动参数以选择使用本地view
2 编译的时候可以选择两个都编译，也可以单个编译
谢谢了。

**Comment by shugen002** [comment]
从我碰过的项目看是可以，具体我也没自己设置过，希望您摸索完后带带我，还有上面那个page怎么设置，也稍微分享下，谢谢。
**你忘记改代码中的地址了**
最好在github.io里面原来的地址上加个跳转页面先吧，作为一个过渡，提示他们改收藏夹地址。。。

后面我也打算提几个PR

**Comment by lzghzr** [comment]
确实忘了还有个302跳转

**Comment by lzghzr** [comment]
跳转已加
