### ISSUE TITLE
添加信息提醒功能

### ISSUE THREAD

**Issue by lzghzr** [lzghzr/bilive_client#65]
目前考虑到实物奖励和账号失效的提醒，其他没考虑到的可以提醒我一下

综合考虑用邮箱推送消息，因为简单，只需要发件人开启SMTP，其他用户弄一个邮箱选项即可
其他方法，如果你是帮朋友代挂的，就很不好处理
@lovezm @sxinxins

**Comment by lovezm** [comment]
只提醒使用者哈？自己设置个163邮箱发给我qq邮箱嘛

**Comment by tzhongyan** [comment]
其实我觉得最简单的做法就是把信息包进POST请求内，随便设置个webhook就好啦

当然，还是不及SMTP方便用户使用。代挂方面要求每个用户都填邮箱不行吗？_(:3」∠)_

**Comment by lovezm** [comment]
为啥要求每个用户填邮箱啊 哪个中奖了直接发到指定邮箱不就行嘛~

**Comment by sxinxins** [comment]
我就自己一个人，没有代挂，简单的一个邮箱就满足了。账号失效是封IP那种的？

**Comment by lzghzr** [comment]
嗯，我的想法就是所有账号都填个邮箱，有情况的时候就发个邮件，同时抄送一份给主人
不过看你们讨论好像更在意主人接到消息，而不是账号，这样的话server酱也未尝不可，但是我记得公众号现在一天只能推送一条消息来的，万一一下中了两个大奖怎么办

**Comment by lovezm** [comment]
server可以推送好多啊。我路由器换IP都是用server推送的。实在不好就smtp吧~ 因为我自己的号一个个设置邮箱也麻烦呀~

**Comment by lzghzr** [comment]
嗯，确实可以，而且使用起来真方便，比邮件还方便

**Comment by youyoudeminger** [comment]
感觉还是邮件好一点

**Comment by youyoudeminger** [comment]
要不然就在根目录下建立一个log专门存账号失效和中奖列表（包括实物和礼物大奖就是10W银瓜子啥的）
