### ISSUE TITLE
无法参与小电视活动抽奖

### ISSUE THREAD

**Issue by Jovy310** [lzghzr/bilive_client#66]
助手有提示，但点击时候出错，手机端显示“访问被拒绝”。
是不是我被封禁了？有办法解决这种问题吗？
求大佬给我讲解一下，还有没有得救？是永久封禁的吗？

**Comment by lzghzr** [comment]
B站开始封禁脚本抽奖了而已，具体情况我也不清楚

**Comment by Jovy310** [comment]
不是啊，我不用脚本了也不能抽奖了

**Comment by darknessice** [comment]
就是封禁了你的抽奖功能，被封的ID不能参与任何抽奖，一般一天左右会解封。
不过也真频繁出错的感觉。

**Comment by lzghzr** [comment]
有人已经解封了？

darknessice <notifications@github.com> 于 2018年3月25日周日 14:17写道：

**Comment by darknessice** [comment]
@lzghzr 看是有人解封。
不知道能不能做个随机暂停抽奖的功能，不一直挂着抽，偶尔能断开一下。

**Comment by AmahaSuzune** [comment]
好像和延迟有关。。。可能故意加一些延迟会好一些

**Comment by lzghzr** [comment]
恩，我试试

AmahaSuzune <notifications@github.com> 于 2018年3月25日周日 17:34写道：

**Comment by lovezm** [comment]
对还是建议延迟 个1秒 或者多少 不过我听说用api就封不知道是不是真的

**Comment by lzghzr** [comment]
全浏览器模拟也可以，不过要耗很多内存就是了，没搞懂封号原理之前不打算这么弄

WangMuDu <notifications@github.com> 于 2018年3月25日周日 19:20写道：

**Comment by Jovy310** [comment]
确实，一天我没用脚本之后，我的帐号解禁了。

**Comment by lovezm** [comment]
还是建议先暂时设置延迟 不要太快抢了 我一个朋友就是的 弄了延迟 封的很少 虽然抢的慢 只要有就行了  没有的话 少点也比被屏蔽好

**Comment by lzghzr** [comment]
只是延迟的话很好加，还有server酱也弄完了，不过我忘了小电视抽奖中实物的gift id是多少了

**Comment by lovezm** [comment]
23333哈哈 能不能通过文字判断了

**Comment by lovezm** [comment]
建议先把延迟弄一下吧~不懂nodejs 不知道咋改他，貌似抢的慢一点不会出问题。

**Comment by youth1996** [comment]
刚抓了下，小电视实物是 gift-b

**Comment by lzghzr** [comment]
我用文字了

youth1996 <notifications@github.com> 于 2018年3月27日周二 15:08写道：

**Comment by yanjun0501** [comment]
我现在只提示有抽奖 但是不参与 是被封了么 23333

**Comment by yimshing** [comment]
![qq 20180328182651](https://user-images.githubusercontent.com/19247568/38023771-b952b6f2-32b5-11e8-8cfd-385ba7993e7c.png)

中午开始 只提示但没有抽中

**Comment by lzghzr** [comment]
看起来加延时也没什么卵用

yimshing <notifications@github.com> 于 2018年3月28日周三 18:28写道：

**Comment by lovezm** [comment]
破站要上市就膨胀啊。

**Comment by BugKun** [comment]
我觉得User-Agent上可以做一些混淆，例如：浏览器版本号，客户端版本号 在一段区间内随机生成。浏览器可以考虑增加火狐，edge这样的User-Agent。
在设置账号时，为每个不同的账号都生成一个独立不同的User-Agent，并存入options中，方便以后调用。

**Comment by chenwto147** [comment]
![default](https://user-images.githubusercontent.com/37876207/38039753-e269d72c-32e8-11e8-9e60-7b98b7faf228.png)
手动进入房间抽奖的话大概就是这样

**Comment by Naexen** [comment]
很迷了 我所有号里面就剩一个能正常抽。。

**Comment by lzghzr** [comment]
应该没啥用吧，B站要想知道很简单啊，没人会7*24小时不间断抽奖，而且正常用户抽奖会打开直播间，B站对用户点击鼠标的位置也有统计

BugKun <notifications@github.com> 于 2018年3月28日周三 22:27写道：

**Comment by yanjun0501** [comment]
x限制解除了    昨天12点封的 刚刚启动脚本已经可以正常使用了

**Comment by youyoudeminger** [comment]
目前看来延迟没啥用，而且我这边代挂的都有反应掉了很多礼物

**Comment by alexie41** [comment]
直播间进不去但是能抽奖的肯定是脚本，希望脚本能避开这些直播间。

**Comment by k316447978** [comment]
如果我在直播间有操作的时候，他就不封，如果没操作一段时间（比如晚上睡觉），就会封。
但却是一天不封，一天封。

**Comment by lzghzr** [comment]
所以是操作也隔天封，还是操作以后就不封了

k316447978 <notifications@github.com> 于 2018年4月1日周日 12:13写道：

**Comment by k316447978** [comment]
不太清楚，因为我是24小时挂机的。
可以确定的是，我如果早上起床后发现没封，我会挂着直播间，隔一段时候操作几下，如果是凌晨2点睡觉，就可以维持到第二天的凌晨6点左右才封（期间也有小伙伴反映白天封号的，但我并没出现过白天封号）。
但现在的问题是隔一天封一次（凌晨6点封到晚上12点，然后解封当天就不封号），所以我也不知道是因为我有操作的原因不封号还是解封当天不封号，毕竟我没有试过白天封号的。

**Comment by qiu512398604** [comment]
模拟人工进入直播间获取用户信息、获取包裹blablabla那一套做下来就行了

**Comment by lzghzr** [comment]
这几天B站没封号吧，我的几个号什么都没做还是好好的
别说真的是腾讯云免封就行

qiu512398604 <notifications@github.com> 于 2018年4月2日周一 00:13写道：

**Comment by lovezm** [comment]
是没封 不是腾讯云的事情应该，我京东云没事了

**Comment by BugKun** [comment]
其实，我觉得还是直接拿个树莓派来挂机方便，其他的vps在隐私方面，我信不过。。。

**Comment by lovezm** [comment]
那你完了 以后都只能自己托管服务器了。

**Comment by k316447978** [comment]
@lovezm 为什么我完了呀，不过我腾讯云还有3年多才过期，难道现在你们都没被封过了吗？

**Comment by lovezm** [comment]
我说他  如果信不过就只能自己托管  不过人家确实有权限进你服务器

**Comment by BugKun** [comment]
不至于吧，一个树莓派就可以了。只有涉及到个人帐号的，我才在树莓派上挂机，如果是其他类型的项目是还是放提供商的服务器的。

**Comment by lovezm** [comment]
人家没兴趣看我B站账号
![image](https://user-images.githubusercontent.com/10624938/38181163-f38f8000-3663-11e8-9b21-bef3157539a9.png)

**Comment by lzghzr** [comment]
这几天看了一下还是每天少抽一点比较靠谱，我再测试测试

顺便大家是想按概率(80%, 90%这样)来决定是否参与抽奖还是按时间(03:00~08:00不抽这样)来？

**Comment by sxinxins** [comment]
对自己狠一点 概率加时间都要  另外这几天双端都正常

**Comment by sxinxins** [comment]
对自己狠一点  概率和时间都来

**Comment by AppaMoMo** [comment]
@lzghzr 今天中午突然不能抽奖 说下过程
凌晨抽了4根辣条关电脑 ，手机后台挂机升级，早上用手机领完瓜子，10：30左右还手动抽了2根辣条，12点多手机再去抽奖就访问被拒绝了。
所以封禁不是实时的可以确定
这几周的话也只是下午到晚上才用抽奖，抽奖时间也改的随机的，概率和时间应该也没用吧。

**Comment by 1499049630** [comment]
我想知道什么时间才能解封啊 我几个账号都封了几天了

**Comment by Baninn** [comment]
前几天被封了好像有五天（延迟和时间都设定过），后来解了再挂一天又被封了（不知道是不是发弹幕被举报的缘故连弹幕也发不了了（发的别人看不到）），然后就不敢挂了……
