### ISSUE TITLE
感谢坚持每天支付宝扫码的朋友

### ISSUE THREAD

**Issue by lzghzr** [lzghzr/bilive_client#67]
虽然每天红包推广+付款码才两毛钱，不过你的坚持很让我感动啊
所以有需要的话可以支付宝留言的时候告诉我B站账号密码，我帮你挂个亿圆

**Comment by yimshing** [comment]
不用谢

**Comment by sxinxins** [comment]
原谅我今天才注意到二维码，红包已经从0.02→tan90°了，羡慕你们几毛的(*/ω＼*)

**Comment by Vector000** [comment]
有红包的？emm
我记得前段时间给大佬转了个2.33来着=￣ω￣=

**Comment by AmahaSuzune** [comment]
我还能有0.02hhh

**Comment by Jovy310** [comment]
美滋滋啊

**Comment by xuefufu** [comment]
一直忘了这事。。给大佬打6.66表示感谢。

**Comment by yanjun0501** [comment]
大佬 我每天也给你0.02  你可以帮我挂亿元么  233333

**Comment by lzghzr** [comment]
可以啊，我不嫌少

**Comment by yanjun0501** [comment]
@lzghzr okk

**Comment by lovezm** [comment]
我发现支付宝留言留不下账号密码 2333

**Comment by lovezm** [comment]
大佬我给你转了三笔小的 还希望不要嫌弃 帮我挂一下亿元可以吗~账号密码留在转账备注里了。

**Comment by lovezm** [comment]
如果你挂上了我就把我号退掉啦

**Comment by lzghzr** [comment]
我只挂节奏的，你要想抽奖自己挂一下
以及已经不小了，每天0.1就行，我怕你自己都忘了，我还在给你挂

**Comment by lovezm** [comment]
好的 谢谢大佬 那抽奖我自己挂~你帮我挂一下节奏就好啦~

**Comment by lzghzr** [comment]
在我这挂的不要炫耀多少多少，低调点我就不限量

**Comment by lovezm** [comment]
我一个字都不会说出去！

**Comment by Naexen** [comment]
猜到支付宝邮箱了哈哈哈哈

**Comment by lzghzr** [comment]
今天问了一下才意识到代挂的亿圆并不多，我也不知道为什么，还以为都和我一样的😂

**Comment by lzghzr** [comment]
![code_2018-04-11_21-50-14](https://user-images.githubusercontent.com/13391314/38621149-ce029fa4-3dd2-11e8-8c0c-103547f58eb7.png)
![code_2018-04-11_21-51-41](https://user-images.githubusercontent.com/13391314/38621154-d23954dc-3dd2-11e8-9c98-b31321da6a09.png)
![code_2018-04-11_21-52-44](https://user-images.githubusercontent.com/13391314/38621155-d29fe602-3dd2-11e8-9164-b6179900be48.png)
以上分别为我自己的号，朋友的号以及某位捐赠者的号
在我没有主动限制的情况下能差出这么多，我也不知道为什么

之前以为每个号都应该是一样的，还想着都低调点，现在看来没有必要了

**Comment by yimshing** [comment]
我每天稳定40-50左右

**Comment by youyoudeminger** [comment]
l大，你的支付宝账号是啥啊，打算给你赞助，顺便求挂一波节奏

**Comment by lovezm** [comment]
有就不错啦 50都可以+500亲密了~

**Comment by Vector000** [comment]
发现转账留言完全写不下账号密码啥的所以我就直接加支付宝好友了XD

**Comment by alexie41** [comment]
把奖励金顺便给你了

**Comment by lzghzr** [comment]
看起来已经凉了ψ(._. )>

**Comment by 18826223119** [comment]
大大，你支付宝多少，我也想挂(*^▽^*)，每天0.12可以吗

**Comment by lzghzr** [comment]
可以扫二维码啊，不过亿圆已经挂不了多少了，你得有心理准备，不要期望太高

**Comment by lovezm** [comment]
大佬我能再加两个号不.....每天给你多转一点...

**Comment by lovezm** [comment]
谢谢大佬。给俩基友也挂个 嘿嘿

**Comment by lovezm** [comment]
大佬 俩号给你了 ~   如果有时候忘了   - - 隔天补给你哈

**Comment by Jovy310** [comment]
节奏风暴过几个月也要变辣条机了

**Comment by zhouxiaoxiao6** [comment]
大佬还挂节奏嘛

**Comment by lzghzr** [comment]
能挂，只不过收益逐渐降低，比如第一天200第二天就只有70了，第三天就基本没有，B站这样处理还蛮科学的
