### ISSUE TITLE
cookie token 问题

### ISSUE THREAD

**Issue by RollingL** [lzghzr/bilive_client#68]
Mar 29 2018 18:04:49 : 正在测试可用ip
Mar 29 2018 18:04:56 : 可用ip数量为 38
Mar 29 2018 18:04:56 : user222 Cookie已失效
Mar 29 2018 18:04:56 : user222 Token已失效
(node:2128) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec              tion id: 1): TypeError: Cannot read property 'cookies' of undefined
(node:2128) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre              cated. In the future, promise rejections that are not handled will terminate the               Node.js process with a non-zero exit code.

试过删除cookie 也不行

**Comment by lzghzr** [comment]
说一下nodejs版本
以及，可以试着删除options.json

**Comment by RollingL** [comment]
node-v8.9.3-x64

自己编译也试过不行。

**Comment by lzghzr** [comment]
这段报错难道是B站改了登录返回？可是我自己试了一下是可用正常获取cookies的
https://github.com/lzghzr/bilive_client/blob/14254d78e2297589e3f2befdb61a8cad0f1c2c73/bilive/lib/app_client.ts#L266-L276

**Comment by RollingL** [comment]
应该是我账号被ban了，我换了个号就可以成功获取了。

**Comment by lzghzr** [comment]
嗯？还有这种操作？账号直接封停吗

**Comment by RollingL** [comment]
刚退出登录后提示账号异常，改密码后成功获取。
现在正常抽奖。。。

**Comment by RollingL** [comment]
感谢大佬 去给大佬买个鸡腿

**Comment by lzghzr** [comment]
似乎这个问题比较少见，暂时先不管了
