### ISSUE TITLE
反馈一个自动送礼的小问题

### ISSUE THREAD

**Issue by Vector000** [lzghzr/bilive_client#71]

**Comment by Vector000** [comment]
大佬好，有点小问题
现行自动送礼的机制是检查有效期小于24小时的礼物并将其送出
但是一般活动结束时间是在第二天的14:00，所以自动送礼机制会在前一天的14:00之后就把所有的礼物全部送出，就是这个样子，第二天没有足够礼物刷亲密度就很不舒服
建议把user.ts:262的`if (giftData.expireat > 0 && giftData.expireat < 24 * 60 * 60)`改成`if (giftData.expireat > 0 && giftData.expireat < 12 * 60 * 60)`之类的，反正每8小时就就检查一遍XD

**Comment by Vector000** [comment]
像我这种几天不上服务器端看的我觉得还是很有必要的XD

**Comment by lzghzr** [comment]
在14：00失效的礼物，前12小时就是半夜两点，按照程序的逻辑会在第二天08：30送掉
但是在00：00失效的礼物就只会在16：30送一次，如果此次送礼网络有波动，那这一天的礼物就无法送出了
考虑到活动是暂时的，所以一直保持24小时没变

**Comment by Vector000** [comment]
也可以考虑改一下检查频率，改成6h一次或者4h之类的。只是发几个http请求相信占用不了多少资源emm。
或者可以脑洞大开点，用expire_at推出礼物过期的具体时间然后分类讨论23333

**Comment by Vector000** [comment]
emmm确实很阴谋论
不过完全可以结合现行的其他破站API来控制非法请求数，毕竟签到有getsigninfo宝箱有getCurrentTask日常任务有taskinfo，总不能我进几次房间开个用户中心都被封号吧（滑稽）
