### ISSUE TITLE
监听ID和房间号实时更新

### ISSUE THREAD

**Issue by lzghzr** [lzghzr/bilive_client#72]
目前设置界面只有监听ID和监听房间必须重启才能生效
为了统一，更改为实时生效

**Comment by chouchangQWQ** [comment]
设置界面的地址和协议没有默认的么。。

**Comment by lzghzr** [comment]
昨天更新了，支持自动填充，现在readme.md里就是新使用方法

**Comment by 523860169** [comment]
@lzghzr 我部署在vps上，caddy转发ws连接，bilive应该怎么设置
地址是example.com/bilive

**Comment by lzghzr** [comment]
@523860169 没太明白问题

**Comment by lzghzr** [comment]
得益于B站改版，这个功能不需要做了 233
