### ISSUE TITLE
npm start 报错

### ISSUE THREAD

**Issue by VergeDX** [lzghzr/bilive_client#74]
> bilive_client@1.3.9 start /home/vanilla/桌面/bilive_client
> node ./app.js

/home/vanilla/桌面/bilive_client/bilive/index.js:16
    async Start() {
          ^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vanilla/桌面/bilive_client/app.js:2:16)

**Comment by VergeDX** [comment]
npm ERR! Linux 4.13.0-39-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.11.4
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! bilive_client@1.3.9 start: `node ./app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bilive_client@1.3.9 start script 'node ./app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bilive_client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bilive_client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bilive_client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vanilla/桌面/bilive_client/npm-debug.log

**Comment by VergeDX** [comment]
@lzghzr

**Comment by lzghzr** [comment]
nodejs版本过低，建议使用最新LTS

**Comment by VergeDX** [comment]
好的……我原来是直接 apt install node 的……
