### ISSUE TITLE
run build失败

### ISSUE THREAD

**Issue by xuefufu** [lzghzr/bilive_client#76]
vps重装了好几次，debian、ubuntu和centos都试过。不知道怎么解决。
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! bilive_client@1.3.9 build:client: `tsc --locale zh-cn -p ./tsconfig.json && npm-run-posix-or-windows copy:client`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the bilive_client@1.3.9 build:client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-01T06_01_00_125Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! bilive_client@1.3.9 build: `npm run build:client && npm run build:view`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the bilive_client@1.3.9 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-01T06_01_00_297Z-debug.log

  cat /root/.npm/_logs/2018-05-01T06_01_00_297Z-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle bilive_client@1.3.9~prebuild: bilive_client@1.3.9
6 info lifecycle bilive_client@1.3.9~build: bilive_client@1.3.9
7 verbose lifecycle bilive_client@1.3.9~build: unsafe-perm in lifecycle true
8 verbose lifecycle bilive_client@1.3.9~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/bilive_client/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle bilive_client@1.3.9~build: CWD: /root/bilive_client
10 silly lifecycle bilive_client@1.3.9~build: Args: [ '-c', 'npm run build:client && npm run build:view' ]
11 silly lifecycle bilive_client@1.3.9~build: Returned: code: 137  signal: null
12 info lifecycle bilive_client@1.3.9~build: Failed to exec build script
13 verbose stack Error: bilive_client@1.3.9 build: `npm run build:client && npm run build:view`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid bilive_client@1.3.9
15 verbose cwd /root/bilive_client
16 verbose Linux 2.6.32-042stab126.2
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v8.11.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 137
22 error bilive_client@1.3.9 build: `npm run build:client && npm run build:view`
22 error Exit status 137
23 error Failed at the bilive_client@1.3.9 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]

**Comment by lzghzr** [comment]
感觉问我还不如[百度](https://blog.csdn.net/yuzhongzi81/article/details/51900187)来的方便
