### ISSUE TITLE
直播礼物将要大改

### ISSUE THREAD

**Issue by wordlesswind** [lzghzr/bilive_client#79]
![-2b08fd69a399b46b__01](https://user-images.githubusercontent.com/9050713/39823755-4bad4eb8-53e0-11e8-8340-f74593d62246.jpg)

**Comment by wordlesswind** [comment]
@shugen002
不在

**Comment by lzghzr** [comment]
估计是要增强氪金体验吧，不是已经所有白嫖道具都变成辣条了吗

**Comment by wordlesswind** [comment]
http://api.live.bilibili.com/gift/v3/live/gift_config

**Comment by shugen002** [comment]
这个接口我们已经留意到了，谢谢

**Comment by Jovy310** [comment]
是一波针对氪金体验的，白嫖辣条党没毛病。

**Comment by lzghzr** [comment]
预览版客户端甚至没有银瓜子礼物了，体验直线提升
