### ISSUE TITLE
bilibili直播间监听数量能增加到每个分区1个房间？

### ISSUE THREAD

**Issue by xxxxuanran** [lzghzr/bilive_client#81]
挂在3号直播间和1040号直播间，发现3号只会提示娱乐分区的xds和大楼，而1040号只会提示手游分区的xds和大楼，请问能开多房间监听吗=-=

修改：挂了30分钟后发现，是摩天大楼只向本分区所有开播房间推送

**Comment by lzghzr** [comment]
还有这种事情吗？我观察一下

**Comment by aliofwind** [comment]
初步观察是摩天大楼只向同一分区下的开播房间推送公告

**Comment by lzghzr** [comment]
确实是这样……这招真是没想到

**Comment by Vector000** [comment]
才发现这个问题，我已经写了一个勉强能用的XD 先测试一下再提PR

**Comment by 00sky** [comment]
大佬，现在分区变成六个分区了。能加个实时获取6个分区正在直播的房间吗？
