### ISSUE TITLE
小电视漏抽？

### ISSUE THREAD

**Issue by tt508618** [lzghzr/bilive_client#84]
好像如果有大佬在网页选择一次性送几个小电视就只会抽最后一个？前面的都漏掉了？

**Comment by tt508618** [comment]
是自己编译！这中间就漏了两个。
![4g cggtim2 o3se 7s_op8o](https://user-images.githubusercontent.com/30516411/40846108-386316d6-65eb-11e8-8932-13eccd92cf1a.png)

**Comment by tt508618** [comment]
@lzghzr

**Comment by lzghzr** [comment]
好，我观察一下

**Comment by yjqiang** [comment]
小电视获取信息那里请问您使用了cookie么？https://api.live.bilibili.com/gift/v3/smalltv/check?roomid={real_roomid}   返回的status正常是1表示未抽，2表示已经抽取，然而观察到错误返回情况，返回2但是没有抽取。

**Comment by lzghzr** [comment]
获取信息不需要cookie

**Comment by yjqiang** [comment]
那么重复抽奖问题的解决方法就是使用list去搜索了么。。。这是一个很蛋疼的办法吧

**Comment by lzghzr** [comment]
很简单啊，id递增的，不重复就好了，如果你在其他位置抽奖了，那这个程序不会做任何判断，依然会去抽奖

**Comment by yjqiang** [comment]
id并不是递增的，有的时候7之后紧接着是9，之后是8，观察过这种情况。

**Comment by yjqiang** [comment]
当然这有可能是推送顺序导致的，但是这的确存在的。

**Comment by lzghzr** [comment]
有可能几个大佬一起送了N多小电视，id并不按照递增排序，所以才有这个issue啊
这是B站广播的问题，而且感觉修复这个问题不是很有价值，要么增加api请求，每次抽奖前都坚持是否参与，要么就像现在一样，最多再优化一下id的排序

**Comment by yjqiang** [comment]
建议使用cookie或者维护一个list，后者可靠；前者要依靠b站不sb，但是目前来看，还算可靠，也比较优雅吧。

**Comment by cris3980** [comment]
好像我挂在国外的centos服务器漏抽比较严重，一天能差一半，但是国外的好像没那么容易进小黑屋

**Comment by cris3980** [comment]
确认了一下，是摩天大楼漏了，或许一个分区多监控几个房间会好点，一天大概能漏200多

**Comment by sxinxins** [comment]
不过，监听的房间多了，怕被盯上关小黑屋

**Comment by cris3980** [comment]
听说国外服务器挂不进黑屋，我这两天弄了个确实原来会进的号就不进了

**Comment by lzghzr** [comment]
@cris3980 估计是不会包邮所以不封号？

**Comment by cris3980** [comment]
这个就不知道了，旧的API封1天新的封5天，我国内是tx的服务器，原来不封的，最近半个月开始封，但是有几个号很坚挺，好像都是氪金号

**Comment by S-H-Y-GitHub** [comment]
充钱的确可以解封，前几天一直都封着，我充了5块钱然后到现在都没有再次被封

**Comment by xxxxuanran** [comment]
我还以为就我一个这样=-=...话说自从换到v4的api之后漏抽越来越严重，10个小电视这种干脆不参与，监听能监听到...=-=

**Comment by cris3980** [comment]
监听到的不会漏的，除非是关闭时间或者小黑屋封号，监听漏的都是摩天大楼

**Comment by xxxxuanran** [comment]
不...昨天10个xds，监听全监听到但是序号是乱的。但是只有第一个和第十个有返回抽奖获得辣条，去到房间也剩下8个xds。=-=

**Comment by BlueJuest** [comment]
![qq 20180616174054](https://user-images.githubusercontent.com/35946889/41497675-b65f1362-718c-11e8-937d-56ec59195956.png)
好像是漏抽严重

**Comment by cris3980** [comment]
这些漏的都是大楼的

**Comment by xxxxuanran** [comment]
突然发现xds的v2,v3,v4api好像都能抽一次=-=....？隔壁打听来的

**Comment by cris3980** [comment]
抽奖丢国内，签到、宝箱、任务丢国外完美不黑屋不漏抽

**Comment by cris3980** [comment]
100连C位漏掉90%
Jul 26 2018 23:59:04 : 房间 82608 开启了第 92364 轮C位光环抽奖
Jul 26 2018 23:59:14 : 房间 516043 开启了第 92365 轮C位光环抽奖
Jul 26 2018 23:59:22 : x 丢弃抽奖 92365
Jul 26 2018 23:59:22 : 房间 526 开启了第 92383 轮专属C位光环抽奖
Jul 26 2018 23:59:22 : 房间 526 开启了第 92412 轮专属C位光环抽奖
Jul 26 2018 23:59:22 : 房间 526 开启了第 92455 轮专属C位光环抽奖
Jul 26 2018 23:59:22 : 房间 526 开启了第 92461 轮专属C位光环抽奖
Jul 26 2018 23:59:22 : 房间 526 开启了第 92463 轮专属C位光环抽奖
Jul 26 2018 23:59:22 : 房间 526 开启了第 92465 轮专属C位光环抽奖
Jul 26 2018 23:59:30 : x 丢弃抽奖 92383
Jul 26 2018 23:59:30 : x 丢弃抽奖 92461
Jul 26 2018 23:59:30 : x 丢弃抽奖 92461
Jul 26 2018 23:59:30 : x 丢弃抽奖 92463
Jul 26 2018 23:59:36 : 房间 1010 开启了第 92466 轮摩天大楼抽奖
Jul 26 2018 23:59:37 : 房间 179 开启了第 92467 轮C位光环抽奖
