### ISSUE TITLE
抽奖api修改？

### ISSUE THREAD

**Issue by xxxxuanran** [lzghzr/bilive_client#86]
更新手机端5.27.0之后，需要在直播间等待倒计时，之后直接领取辣条。
目前旧版和PC段仍是加入抽奖，不知道何时会更换api。

补充：用5.9.1版本进去抽奖，能直接领取辣条，但是是限时七天的。有较大几率奖励已经领完。

补充2：新版app等待领取的辣条也是七天。

补充3：v4的api似乎能绕过小黑屋抽奖。

**Comment by lzghzr** [comment]
嗯，我也发现可以绕过黑屋，应该是bug吧，大概周一就修复了（如果B站不加班

**Comment by mscststs** [comment]
等待抽奖这一招……怕不是还是和海鲜台学的吧

**Comment by lzghzr** [comment]
啊，这几天还在测试连麦PK呢

**Comment by diaosimiao** [comment]
报告LZ队长我又被放出来了 手动抽奖和宝箱成功 安全起见再观察几天 半个月来别的程序猿代码问题库也好多人反映被ban 瑟瑟发抖

**Comment by zhanglei541120** [comment]
你们是怎么弄到这些api的呢？
