### ISSUE TITLE
请问您是怎么解决高并发下的403问题的

### ISSUE THREAD

**Issue by yjqiang** [lzghzr/bilive_client#88]
如题

**Comment by lovezm** [comment]
我记得l大说了好像是那些代理ip还是cdn啥的

**Comment by lzghzr** [comment]
#43

**Comment by yjqiang** [comment]
@lzghzr 加入了cdn之后，对于密集抽奖请求时仍然会有403（有效cdn在47左右），我看到 https://github.com/lzghzr/bilive_client/pull/43/commits/7c958bc1f6d4ac3fbc8e6a4740ae10abd635b705，
这里的措施没太看懂，因为抽奖请求是同时向所有用户广播的，那么怎么保证尽量让用户不要凑在一起、密集时间段抽奖呢？

**Comment by lzghzr** [comment]
47个有效CDN还会限制的话，你是挂了多少账号啊😱
这个量挂400个账号没问题吧，除外B站现在有了新的限制

**Comment by yjqiang** [comment]
但是有一个问题在于，请求之间比如1号小电视抽奖与2号小电视的房间进入操作可能存在重复行为，类似的事情会导致行为叠加，所以可能400用户存在几乎同时的800请求量，mmp，403了就

**Comment by lzghzr** [comment]
可以无脑加IP，昨天重新扫了一遍，大概有80多个
这样要解决的就是性能问题了，上千个请求就这么发出去多半会死一片
