### ISSUE TITLE
被封禁了？

### ISSUE THREAD

**Issue by zhzh16** [lzghzr/bilive_client#89]
日志里有显示参与，包裹里没有增加，瓜子手动领取显示访问被拒绝，是不是脚本被检验出来，惨遭封禁了？

**Comment by zhzh16** [comment]
浏览器控制台显示 Failed to load https://api.live.bilibili.com/msg/getSuser: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://live.bilibili.com' is therefore not allowed access.
vendor.2cf8891823712a0aee52.js:46 [Error] 直播心跳请求错误: undefined - undefined

**Comment by lzghzr** [comment]
封禁一直都存在的，看不顺眼就被封了

**Comment by 10lumiya10** [comment]
这两天查得有点严，被放出来一天后又被封了，还是早上6点到7点封的，然后看log发现总督抽奖没被封，是总督抽奖太少了B站懒得封吗 @lzghzr 

Jul 13 2018 11:09:13 : 房间 5551515 开启了第 345137 轮总督抽奖
Jul 13 2018 11:10:19 : 总督抽奖 345137 当前佩戴的粉丝勋章亲密度+20~

**Comment by xxxxuanran** [comment]
我在怀疑你是不是不看B站直播的....
总督亲密度领取不受小黑屋影响
上面的心跳请求错误大概率是你网络问题

**Comment by OiCkilL** [comment]
我挂的几个号看来都全黑了
`Jul 16 2018 09:48:23 : 房间 4167830 开启了第 77678 轮小电视飞船抽奖
Jul 16 2018 09:51:54 : 房间 479 开启了第 77679 轮C位光环抽奖
Jul 16 2018 09:55:55 : 房间 489 开启了第 77680 轮C位光环抽奖
Jul 16 2018 09:56:04 : 房间 696095 开启了第 77681 轮C位光环抽奖
Jul 16 2018 10:00:32 : 房间 316483 开启了第 77682 轮C位光环抽奖
Jul 16 2018 10:00:53 : 房间 489 开启了第 77683 轮C位光环抽奖
Jul 16 2018 10:01:32 : 房间 479 开启了第 77684 轮摩天大楼抽奖
Jul 16 2018 10:01:45 : 房间 3942965 开启了第 77685 轮C位光环抽奖
Jul 16 2018 10:04:12 : 房间 489 开启了第 77686 轮C位光环抽奖
Jul 16 2018 10:04:48 : 房间 1313362 开启了第 77687 轮C位光环抽奖
Jul 16 2018 10:06:18 : 房间 479 开启了第 77688 轮摩天大楼抽奖
Jul 16 2018 10:06:37 : 房间 489 开启了第 77689 轮C位光环抽奖
Jul 16 2018 10:09:44 : 房间 489 开启了第 77690 轮C位光环抽奖
Jul 16 2018 10:09:54 : 房间 479 开启了第 77691 轮C位光环抽奖
Jul 16 2018 10:10:18 : 房间 479 开启了第 77692 轮摩天大楼抽奖
Jul 16 2018 10:10:18 : 火车头 丢弃抽奖 77692
Jul 16 2018 10:11:26 : 房间 4196663 开启了第 77693 轮摩天大楼抽奖
Jul 16 2018 10:11:48 : 房间 4167830 开启了第 77694 轮C位光环抽奖
Jul 16 2018 10:12:21 : 房间 982077 开启了第 77695 轮C位光环抽奖
Jul 16 2018 10:13:01 : 房间 489 开启了第 77696 轮C位光环抽奖
Jul 16 2018 10:14:00 : 房间 479 开启了第 77697 轮C位光环抽奖
Jul 16 2018 10:16:16 : 房间 489 开启了第 77698 轮C位光环抽奖
Jul 16 2018 10:17:11 : 房间 2839822 开启了第 77699 轮C位光环抽奖
Jul 16 2018 10:19:36 : 房间 5085 开启了第 77700 轮C位光环抽奖
Jul 16 2018 10:19:45 : 房间 4196663 开启了第 77701 轮C位光环抽奖
Jul 16 2018 10:20:10 : 房间 489 开启了第 77702 轮C位光环抽奖
Jul 16 2018 10:24:19 : 房间 42853 开启了第 77703 轮C位光环抽奖
Jul 16 2018 10:28:53 : 房间 982077 开启了第 77704 轮C位光环抽奖
Jul 16 2018 10:30:18 : 房间 489 开启了第 77705 轮C位光环抽奖
Jul 16 2018 10:31:40 : 房间 2839822 开启了第 77706 轮C位光环抽奖
Jul 16 2018 10:31:40 : 万万 丢弃抽奖 77706
Jul 16 2018 10:32:56 : 房间 479 开启了第 77707 轮C位光环抽奖
Jul 16 2018 10:33:37 : 房间 489 开启了第 77708 轮C位光环抽奖
Jul 16 2018 10:34:06 : 房间 3580061 开启了第 77709 轮C位光环抽奖
Jul 16 2018 10:34:49 : 房间 8369949 开启了第 77710 轮C位光环抽奖
Jul 16 2018 10:34:53 : 房间 8369949 开启了第 77711 轮C位光环抽奖
Jul 16 2018 10:34:55 : 万万#2 C位光环抽奖 77707 获得 2 个辣条
Jul 16 2018 10:36:53 : 房间 489 开启了第 77712 轮C位光环抽奖
Jul 16 2018 10:38:46 : 房间 479 开启了第 77713 轮C位光环抽奖
Jul 16 2018 10:38:54 : 房间 3580061 开启了第 77714 轮C位光环抽奖
Jul 16 2018 10:39:28 : 房间 491 开启了第 77715 轮C位光环抽奖
Jul 16 2018 10:40:40 : 房间 4389425 开启了第 77716 轮摩天大楼抽奖
Jul 16 2018 10:43:01 : 房间 2839822 开启了第 77717 轮C位光环抽奖
Jul 16 2018 10:45:14 : 房间 4870575 开启了第 77718 轮C位光环抽奖
Jul 16 2018 10:46:30 : 房间 489 开启了第 77719 轮C位光环抽奖
Jul 16 2018 11:00:29 : 房间 4198132 开启了第 77720 轮摩天大楼抽奖
Jul 16 2018 11:01:12 : 房间 291 开启了第 77721 轮C位光环抽奖
Jul 16 2018 11:01:45 : 房间 982077 开启了第 77722 轮C位光环抽奖
Jul 16 2018 11:02:17 : 房间 42853 开启了第 77723 轮C位光环抽奖
Jul 16 2018 11:02:17 : 火车头 丢弃抽奖 77723
Jul 16 2018 11:07:56 : 房间 489 开启了第 77724 轮C位光环抽奖
Jul 16 2018 11:08:00 : 房间 489 开启了第 77725 轮C位光环抽奖
Jul 16 2018 11:08:00 : 渣渣辉 丢弃抽奖 77725
Jul 16 2018 11:08:04 : 房间 489 开启了第 77726 轮C位光环抽奖
Jul 16 2018 11:08:08 : 房间 489 开启了第 77727 轮C位光环抽奖
Jul 16 2018 11:08:12 : 房间 489 开启了第 77728 轮C位光环抽奖
Jul 16 2018 11:12:52 : 房间 4198132 开启了第 77729 轮C位光环抽奖
Jul 16 2018 11:14:51 : 房间 479 开启了第 77730 轮C位光环抽奖
Jul 16 2018 11:21:34 : 房间 4198132 开启了第 77731 轮小电视飞船抽奖
Jul 16 2018 11:23:16 : 房间 3567937 开启了第 77732 轮C位光环抽奖
Jul 16 2018 11:24:57 : 房间 4198132 开启了第 77733 轮C位光环抽奖
Jul 16 2018 11:27:10 : 房间 5509332 开启了第 77734 轮C位光环抽奖
Jul 16 2018 11:28:17 : 房间 4198132 开启了第 77735 轮小电视飞船抽奖
Jul 16 2018 11:28:17 : 万万 丢弃抽奖 77735
Jul 16 2018 11:31:24 : 房间 16405 开启了第 77736 轮C位光环抽奖
Jul 16 2018 11:33:38 : 房间 1122474 开启了第 77737 轮C位光环抽奖
Jul 16 2018 11:33:38 : 渣渣辉 丢弃抽奖 77737
Jul 16 2018 11:33:38 : 万万 丢弃抽奖 77737
Jul 16 2018 11:35:59 : 房间 3297956 开启了第 77738 轮C位光环抽奖
Jul 16 2018 11:38:17 : 房间 4198132 开启了第 77739 轮摩天大楼抽奖
Jul 16 2018 11:38:47 : 房间 659 开启了第 77740 轮C位光环抽奖
Jul 16 2018 11:49:57 : 房间 12306168 开启了第 77741 轮C位光环抽奖
Jul 16 2018 11:54:55 : 房间 10259632 开启了第 77742 轮C位光环抽奖
Jul 16 2018 11:54:55 : 万万 丢弃抽奖 77742
Jul 16 2018 11:56:29 : 房间 3297956 开启了第 77743 轮C位光环抽奖
Jul 16 2018 12:19:25 : 房间 1508259 开启了第 77744 轮C位光环抽奖
Jul 16 2018 12:25:32 : 房间 479 开启了第 77745 轮C位光环抽奖
Jul 16 2018 12:26:03 : 房间 3567937 开启了第 77746 轮摩天大楼抽奖`
