### ISSUE TITLE
(｀・ω・´)

### ISSUE THREAD

**Issue by brina60602** [lzghzr/bilive_client#9]
作者(｀・ω・´)有沒有甚麼方法開機執行 node app.js  ?
比如 做個執行檔 放到啟動資料夾

**Comment by lzghzr** [comment]
这个问题找搜索引擎更好一些
[Google](https://www.google.com/search?q=node+%E9%96%8B%E6%A9%9F%E5%95%93%E5%8B%95)
[Baidu](https://www.baidu.com/baidu?wd=node%20%E9%96%8B%E6%A9%9F%E5%95%93%E5%8B%95)
