### ISSUE TITLE
反馈一个小问题

### ISSUE THREAD

**Issue by Vector000** [lzghzr/bilive_client#90]
listener:83的`this._DMclient.delete(areaRoomID)`实际是无效的，并不能在`Map()`里将对应的`DMclientRE`类型删除，因为在`this._DMclient`里实际对应的key是`areaID`。应该是`this._DMclient.delete(areaID)`

在现行逻辑下对监听效果还是有一点影响的

有漏抽现象可以考虑监听`cmd: PREPARING`下播事件，更换房间；或者增大分区房间检查频率

**Comment by lzghzr** [comment]
嗯，我自己都忘了这个设定了……

**Comment by Vector000** [comment]
这个无脑加监听真是绝了，每分区都监听3个房间_(:3」∠)_

**Comment by lzghzr** [comment]
后面会优化一下，要不然一个小电视12个重复请求，IP再多也不能这么浪费
