### ISSUE TITLE
C位光环活动抽奖

### ISSUE THREAD

**Issue by syu1230** [lzghzr/bilive_client#91]
最近的活动，C位光环的抽奖能加一下吗

**Comment by brina60602** [comment]
(｀・ω・´)
![image](https://user-images.githubusercontent.com/15816106/42732151-238eaf2e-884e-11e8-93f8-5700064eafe1.png)

**Comment by lzghzr** [comment]
明明就有，不需要更新的

**Comment by brina60602** [comment]
一次這麼多個會全都抽嗎?
(｀・ω・´)
![image](https://user-images.githubusercontent.com/15816106/42735451-a4ef2fc0-8886-11e8-9a0b-214e5c678ca8.png)

**Comment by jessiepool** [comment]
请问为什么我只能检测到小电视呢？下载的是最新版本啊。
