### ISSUE TITLE
希望增加新功能

### ISSUE THREAD

**Issue by ShmilyChen** [lzghzr/bilive_client#95]
@lzghzr 希望大佬可以把@Vector000 做的自动送礼V2合并进入主线

**Comment by izcbc** [comment]
@lzghzr 昨天git pull后遇到个bug，设置的2,3,4,5,6,7,8,9   结果4点多还是会自动抽，被钓鱼进屋了

**Comment by xifan-fh** [comment]
我今天刚出来，进去差不多一周了

**Comment by ShmilyChen** [comment]
@Vector000 的疯狂被钓鱼
很难受

**Comment by Vector000** [comment]
哎，怎么突然被艾特
