### ISSUE TITLE
( ° ∀ ° ) ﾉ

### ISSUE THREAD

**Issue by brina60602** [lzghzr/bilive_client#97]
我把打開方式做成exe檔了( ｀・ ω ・ ´ )
可惜打開是dos  不能放圖片上去
![image](https://user-images.githubusercontent.com/15816106/43589207-d102a272-96a0-11e8-9589-2ceaaf3736f5.png)
链接: https://pan.baidu.com/s/1l_1XlFX6WwcJB1Vm-YCCxg 密码: 4imr
![image](https://user-images.githubusercontent.com/15816106/43588781-ce6ef39a-969f-11e8-993d-b5d2c4b0c75b.png)
![image](https://user-images.githubusercontent.com/15816106/43639156-e34500bc-974d-11e8-8052-be7be52eb5fd.png)
![image](https://user-images.githubusercontent.com/15816106/43588982-4a3f7936-96a0-11e8-9786-88d3d4820b57.png)

**Comment by brina60602** [comment]
![image](https://user-images.githubusercontent.com/15816106/43591383-d1e04cd0-96a5-11e8-9443-c88cf8b85c34.png)

**Comment by brina60602** [comment]
不知群暉把options.json放在哪裡

**Comment by zanewayne78** [comment]
别人分享的exe程序敢下载？

**Comment by brina60602** [comment]
確實←◡←

**Comment by lzghzr** [comment]
嗯，群晖不能直接打开cmd吗
