### ISSUE TITLE
硬币兑换挂了

### ISSUE THREAD

**Issue by cris3980** [lzghzr/bilive_client#98]
`</body></html>
Aug 04 2018 08:30:21 : X 银瓜子兑换硬币 兑换失败 <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<html lang="zh-cn"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="Page-Enter" content="blendTrans(Duration=0.5)">
<meta http-equiv="Page-Exit" content="blendTrans(Duration=0.5)">

<title>维护中 - live.bilibili.com</title>
<style type="text/css">
body { vertical-align: middle; }
div.center { position:absolute; top:50%; left:50%; margin:-25% 0 0 -320px; width:640px; min-height: 427px; padding: 0px; }
div.errmsg { text-align:left; width:640px; line-height:150%;}
a { text-decoration: none; color:red }
a:hover { text-decoration: underline; }
</style>
</head>
<body style="direction: ltr;">
<div class="center">
<img id="img_error" src="http://static.hdslb.com/error/444.png" height="427" width="640"><br>`

**Comment by lzghzr** [comment]
看样子是被和谐了吧

**Comment by Zreo4** [comment]
旧版手动还可以领
